### ISSUE TITLE
ValueError: Inputs/targets with missing values detected on predict with autoregression

### ISSUE THREAD

**Issue by luistelmocosta** [ourownstory/neural_prophet#1050]
Hello, I am trying to fit a neural prophet model into a weekly basis dataset. 

```
curr_date = df['ds'].max() - pd.DateOffset(weeks=8)
m = NeuralProphet(n_changepoints = 230, n_lags=6, newer_samples_weight=5, n_forecasts=1)

m = m.add_events(['holiday1', 'holiday2', "holiday3", 'holiday4',
       'holiday5', 'event1', 'event2',
       'event3', 'event4', "event5", "event6"], mode='multiplicative')


history_df = m.create_df_with_events(df[['ds', 'y']], pd.concat([promotions_df, holidays_df]))
df_train = history_df[history_df['ds'] < np.datetime64(curr_date)]#.reset_index(drop=True)
df_valid = history_df[(history_df['ds'] >= np.datetime64(curr_date)) & (history_df['ds'] <= np.datetime64(curr_date + pd.DateOffset(weeks=8)))]#.reset_index(drop=True)

metrics = m.fit(df=df_train, validation_df=df_valid, freq="W", progress="plot-all")
```

Everything works fine, I am enabling AR-Net by setting a `n_lags` to 6. `n_forecasts` is set to 1. 

However, when I try to `predict` my `df_valid` data frame, I always get the following error:

`ValueError: Inputs/targets with missing values detected. Please either adjust imputation parameters or set 'drop_missing' to True to drop those samples. `

This is how I am running my validation:

```
valid_preds = [] #list to store predictions
lags = 6

for d in df_valid['ds'].values:
  print(d)
  # getting necessary df rows
  date_index = history_df.index[history_df['ds'] == d][0]
  future = history_df.iloc[date_index-lags:date_index]
  print(future.shape)
  # adding new row
  entry = pd.DataFrame({
      'ds': [d],
      'y' : [np.nan]
  })
  future = pd.concat([future, entry], ignore_index = True, axis = 0)
  print(future)
  # making prediction
  forecast = m.predict(df=future)
  valid_preds.append(forecast.loc[lags]['yhat1'])
```

From what I could see, this is the correct way to run the prediction when we set `n_lags`. 

The future dataset from the print returns something like this:

![image](https://user-images.githubusercontent.com/7799750/206288954-1f651020-0583-416f-a868-e8df1106f0be.png)

The 6 weeks from the n_lags and 1 for the n_forecast to work. 

I believe this is happening because of my holidays/events. When creating the future date, the dataset does not return the columns regarding the events.

What am I doing wrong? How do I make my fitted forecast run on my `df_valid` dataframe using Autoregression? Do I need to fill that `entry` with the actual week? 

Kind regards,
Luís

**Comment by judussoari** [comment]
Hi @luistelmocosta, thanks for reporting this. I think it looks somewhat similar to Issue #1027. 
We have merged a PR fixing this, and the new Neuralprophet release is already on its way. Please check whether this problem still occurs after version 0.5.0 has launched, and feel free if it does :)
