### ISSUE TITLE
Global-local warning logged every training batch

### ISSUE THREAD

**Issue by karl-richter** [ourownstory/neural_prophet#1053]
The log in denormalize() in time_net.py is logged every batch. When training on a large dataset, this results in thousands of logs.

Could we simply remove it @alfonsogarciadecorral 

Line 1293 in `time_net.py`
```python
if not self.config_normalization.global_normalization:
     log.warning("When Global modeling with local normalization, metrics are displayed in normalized scale.")
else:
     ...
```

**Comment by alfonsogarciadecorral** [comment]
Hey Karl!

I didn't create that bit of code, so maybe not the best person to answer :(
