### ISSUE TITLE
[bug] Computation bottleneck for large datasets with multiple time series/IDs

### ISSUE THREAD

**Issue by judussoari** [ourownstory/neural_prophet#1057]
For my dataset (2 million entries, >30 different IDs), we currently run into a significant bottleneck that is caused by something prior to model training. Before model training starts, it somehow processes the data for >2mins. 

Edit: my first suspicion is related to the fourier terms of seasonality. increasing the number of fourier terms for x`_seasonality` leads to a significant increase in overhead time

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
