### ISSUE TITLE
NeuralProphet on Databricks - new version progress bar crashing entire notebook

### ISSUE THREAD

**Issue by luistelmocosta** [ourownstory/neural_prophet#1063]
Hello, since I installed the latest NeuralProphet (0.5.0) when I run the fit method like this: `m.fit(df=df_train, validation_df=df_valid, freq="W")`, the entire notebook crashes with the number of progress bars being loaded.

![image](https://user-images.githubusercontent.com/7799750/207037753-f84da099-277c-4f62-aae9-d3c9feb33e2e.png)

This is the final output that I get:

![image](https://user-images.githubusercontent.com/7799750/207079366-d3061982-340b-4363-ace1-df60a1948e7a.png)

Is there any way to run the fit function in a "less verbose" way to run this function and return the metrics values?

Kind regards

**Comment by karl-richter** [comment]
Hi @luistelmocosta, thanks for raising this issue! This seems to be an issue in Pytorch Lightning with the propagates to our application. There is a method to deactivate the progress bar by setting `progress=None` on the fit method. However, there is a small issue with that (already merged #1059). You can either install NeuralProphet from github for now + we will make a new pre-release later today / this week. Will keep you posted on that.
