### ISSUE TITLE
Neural Prophet does not work with (n_forecasts=1, n_lags=0) parameters set.

### ISSUE THREAD

**Issue by vfrankswood** [ourownstory/neural_prophet#1068]
***Neural Prophet  is throwing  ```ValueError: Invalid frequency: NaT ``` on (n_forecasts=1, n_lags=0) parameters while calling .predict() method***

**To Reproduce**

```
import pandas as pd
from neuralprophet import NeuralProphet

dates = ['2020-01-15', '2020-01-16', '2020-01-17', '2020-01-18']
values = [100, 120, 140, 150]

data = {'ds': dates, 'y': values}
df = pd.DataFrame(data)
df['ds'] = pd.to_datetime(df['ds'])

model = NeuralProphet(n_lags=0, n_forecasts=1)
model.fit(df)
future = model.make_future_dataframe(df=df, periods=1)
model.predict(future) 
```

I did the same on real datasets and it still does not work.

**Comment by vfrankswood** [comment]
It seems that the error shows up whenever future dataframe contains one raw only.

**Comment by judussoari** [comment]
Thanks for reporting this @vfrankswood !
Indeed it looks like you are right, the error pops up when future only contains one row. A quickfix is to insert at least one historic value to the dataframe: `future = model.make_future_dataframe(df=df, periods=1, n_historic_predictions=1)`. 
I will try to have a further look into this

**Comment by ourownstory** [comment]
Seems like the frequency auto-detection fails in this case? @MateusGheorghe 

Setting the frequency should resolve this. Please let us know if it does. @vfrankswood 
`freq="D"`

**Comment by martinbel** [comment]
it doesn't work if you set the frequency either.
