### ISSUE TITLE
Make future dataframe with n_forecasts 

### ISSUE THREAD

**Issue by luistelmocosta** [ourownstory/neural_prophet#1077]
Hello, I am currently exploring neural prophet and decided to implement a simple solution where I'm using backtesting in 8 weeks of data with a step of 1 week. 

This is the script that runs the *best* model from the backtest evaluation, params are coming from mlflow. 

```
m = NeuralProphet(**params, n_forecasts=1)
m = m.add_events(['A', 'B', "C", 'D'], mode='multiplicative')


set_random_seed(42)


history_df = m.create_df_with_events(df[['ds', 'y']], pd.concat([promotions_df, holidays_df]))
df_train = history_df[history_df['ds'] < np.datetime64(curr_date)]#.reset_index(drop=True)
df_valid = history_df[(history_df['ds'] >= np.datetime64(curr_date)) & (history_df['ds'] < np.datetime64(curr_date + pd.DateOffset(weeks=8)))]

metrics = m.fit(df=df_train, validation_df=df_valid, freq="W-SUN")
```

After the training process, I run `m.predict()` to see if the `df_valid` performance if the metrics match the evaluation results of the backtest and everything seems ok. 

However, when I try to use my model for inference, I noticed that `make_use_dataframe` only created one additional row, which comes from the `n_forecast` I specified. I didn't expect the `n_forecasts` to have an implication in the creation of my future dataset, so I decided to run the training with `n_forecasts = 4` (my backtest window). 
Then I created my future dataset with `m.make_future_dataframe(df_valid, n_historic_predictions=8)` and I could get my 4 weeks ahead forecast. 

However, I noticed that the results were off compared with the performance I had on my training/validation step and I re-run the previous step, but creating the future from the cutoff training date: `m.make_future_dataframe(df_train, n_historic_predictions=8)` to see if the results would be the same as running the forecast on the `df_valid` directly. 

The results are very different and I don't know what is causing that

Results with validation dataset created with `make_future_dataframe`
![image](https://user-images.githubusercontent.com/7799750/208503991-e8e4391b-b5f9-4928-bac2-daf2dd29bf9f.png)

Results with validation_dataset I provide in the training function above. `m.fit(df=df_train, validation_df=df_valid, freq="W-SUN")` 
![image](https://user-images.githubusercontent.com/7799750/208504140-817e5feb-a571-4d88-b746-d256e8438b30.png)

I would like to have some guidance on how to properly evaluate and use for inference a model using AR. Is this the correct way to create a future dataset for a model with `n_forecasts` > 1? In the fit function when I pass df_valid as validation_df, how is it internally evaluation a model taking into account the `n_forecasts` number?

Thank you!

Kind regards, 
Luís

**Comment by ourownstory** [comment]
Hi @luistelmocosta 
`n_forecasts` sets the number of steps to predict into the future. with `n_lags>0`, this creates a direct regression for each of those steps. 
In your case, you seem to be predicting the next 4 weeks based on the previous four weeks' values. 

Please note that when you split the way you split, you will lack the first `n_lags` inputs to the model. You can use our crossvalidation utility. 
You may find the [testing](https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/test_and_crossvalidate.ipynb) and the [predicting](https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/collect_predictions.ipynb) notebooks useful.

Hope this helps. 
If not, please share a minimal code snippet that helps us re-create the issue you run into.
