### ISSUE TITLE
Fix inconsistency in fit method progress bar parameter

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#1086]
`Flag whether to show a progress bar during training. If None, uses the progress specified in the model config.`

Does `None` not rather disable the progress bar?

https://github.com/ourownstory/neural_prophet/blob/main/neuralprophet/forecaster.py#L701-L707

**Comment by noxan** [comment]
cc @karl-richter

**Comment by ourownstory** [comment]
outdated with move to lightning.
