### ISSUE TITLE
Cannot create make future dataframe with right number of periods

### ISSUE THREAD

**Issue by MariaSdSantos** [ourownstory/neural_prophet#1087]
Hello!

I want to use neural prophet to predict some future values of my dataset. I trained the model like this: 

```python
m = NeuralProphet(num_hidden_layers =0, 
          n_lags=4, 
          newer_samples_weight=1,
          ar_reg = 0, 
          changepoints_range = 0.975, 
          n_changepoints = 140,
          learning_rate = 0.001,
          epochs = 434
                 )
m = m.add_events(['Mid Season', 'Black Friday'], mode='multiplicative')

m.add_future_regressor('week_of_year_sin')
m.add_future_regressor('week_of_year_cos')
m.add_future_regressor('month_sin')
m.add_future_regressor('month_cos')
m.add_seasonality(name='monthly', period=30.5, fourier_order=5)

set_random_seed(42)
train = m.fit(df=history_df, freq="W-SUN")
forecast = m.predict(df=history_df, decompose=True)
```

I now want to predict some future dates (in this case, 4 future weeks), so I use the make_future_dataframe feature like it was advised in the documentation (https://neuralprophet.com/code/forecaster.html#neuralprophet.forecaster.NeuralProphet.make_future_dataframe). However, when I use this, it only gives me one future week.

```python
future = m.make_future_dataframe(df=history_df, periods=4, regressors_df=regressors_df, events_df=events_df)
```
<img width="268" alt="image" src="https://user-images.githubusercontent.com/101735605/209570261-ce0c5c2c-1836-4b5b-9f06-40b1de5210e7.png">

How can I use neural prophet to predict more than 1 week?

Best regards,
Maria

**Comment by judussoari** [comment]
Hey @MariaSdSantos , please specify `n_forecasts=4` in when defining the model `m=NeuralProphet()`. 
Let me know if this solved your issue :) 

All the best,
Júlio

**Comment by judussoari** [comment]
Hey @MariaSdSantos , did it work out eventually? :)
