### ISSUE TITLE
About longterm forecast

### ISSUE THREAD

**Issue by SimyokH** [ourownstory/neural_prophet#1088]
Hi，dear author！
IM new on time-serious forecast and i used neuralprophet for the first time，I have a little question I would like to ask you：
Can neuralprophet handle with long-time-serious forecasting，such as ：Use 3 years of hourly data to forecast hourly data for the coming year？If it can，would u please tell me how to set the parameters?
THANKS！

**Comment by leoniewgnr** [comment]
Hi @SimyokH,
thanks for your question!
In general: if the underlying pattern of the data is represented in the historical data you provide to the model, NeuralProphet should be able to forecast future data. 
For parameters you can check the [documentation](https://neuralprophet.com/quickstart.html) of NeuralProphet. It explains the parameters you can set and also gives examples on how to get started.
If you have any other questions, feel free to join our [slack channel](https://join.slack.com/t/neuralprophet/shared_invite/zt-1iyfs2pld-vtnegAX4CtYg~6E~V8miXw) 
Best,
Leonie

**Comment by leoniewgnr** [comment]
Hi @SimyokH,
thanks for your question!
In general: if the underlying pattern of the data is represented in the historical data you provide to the model, NeuralProphet should be able to forecast future data.
For parameters you can check the [documentation](https://neuralprophet.com/quickstart.html) of NeuralProphet. It explains the parameters you can set and also gives examples on how to get started.
If you have any other questions, feel free to join our [slack channel](https://join.slack.com/t/neuralprophet/shared_invite/zt-1iyfs2pld-vtnegAX4CtYg~6E~V8miXw)
Best,
Leonie
