### ISSUE TITLE
Issue running neurol prophet on Ray or any other parallel strat.

### ISSUE THREAD

**Issue by maximilianolucius** [ourownstory/neural_prophet#1090]
Just make a python enviroment and run the script that capture & how the issue.
Enviroment: python 3.10, current versin of neuronal prophet, and ray==2.1.0

Issue: al the workers freeze on model.fit method.

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

The model object freeze when fit method is executed when running in parallel with Ray library, joblib, or multiprocess library.

**To Reproduce**
Generate and source an env with:
pandas, ray==2.1.0, neuronal_prophet

Run the following script ...

**********************************************************************************************************************
from neuralprophet import NeuralProphet
import datetime
import numpy as np
import pandas as pd
import ray

@ray.remote
def nprophet_ray(data:pd.DataFrame):
    return nprophet_wrapper(data)

def nprophet_wrapper(data: pd.DataFrame):
    m = NeuralProphet(
        weekly_seasonality=6,
        daily_seasonality=10,
        trend_reg=1,
        learning_rate=0.01,
    )
    df_train, df_test = m.split_df(data, freq="H", valid_p=1.0 / 12)
    metrics = m.fit(df_train, freq="H", validation_df=df_test, num_workers=1, # yearly_seasonality=False,
                    batch_size=32, epochs=10)
    forecast = m.predict(df_test)
    return metrics, forecast

if __name__ == '__main__':
    start0 = datetime.datetime(2015, 1, 1)
    delta = datetime.timedelta(hours=1)

    dt = np.array([start0 + i * delta for i in range(10_000)])
    y = np.cos([np.pi * 2 / 1000 * i for i in range(10_000)]) + np.sin([np.pi * 2 / 2500 * i for i in range(10_000)])

    data = pd.DataFrame({'ds': dt, 'y': y}).reset_index(drop=True)

    metrics, forescast = nprophet_wrapper(data)

    ray.init()
    remaining_ids = [nprophet_ray.remote(data.copy()) for _ in range(1)]
    res = ray.get(remaining_ids)

**********************************************************************************************************************

1. With the data '...'
2. Setting the model hyperparameters '....'
3. After running these code lines '....'
4. When using this function '....'
5. See error

**Expected behavior**

**What actually happens**

Describe what happens, and how often it happens.

**Screenshots**

If applicable, add screenshots and console printouts to help explain your problem.

**Environement (please complete the following information):**

 - Python environment [e.g. Python 3.8, in standalone venv with no other packages]
 - NeuralProphet version and install method [e.g. 2.7, installed from PYPI with `pip install neuralprophet`]

**Additional context**

**Comment by karl-richter** [comment]
Hi @maximilianolucius, sorry for the delay. Does this issue still persist?

**Comment by leoniewgnr** [comment]
Closed due to the inactivity
