### ISSUE TITLE
implement basic uncertainty estimation via Quantile Regression

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#11]

**Comment by schlinge2000** [comment]
status?

**Comment by yasirroni** [comment]
> > status?
> > @schlinge2000 should be finally merged soon, right @HansikaPH ?

This feature is really anticipated. Hope it will merge soon.

**Comment by ourownstory** [comment]
@HansikaPH we need you :)

**Comment by qiwei-li** [comment]
I hope this can be merged soon!

**Comment by milannnnn** [comment]
Any news on this one?

**Comment by Kevin-Chen0** [comment]
Latest initiative [here](https://github.com/ourownstory/neural_prophet/pull/669)

**Comment by ourownstory** [comment]
@schlinge2000 @yasirroni @milannnnn @qiwei-li @vincenzomanzoni 
It has finally been merged in #669 !

Please let us know how it works for you.

**Comment by yasirroni** [comment]
Thanks a lot. Any minimal working example to start experimenting? Or at least the name of the main method? Thanks.

@ourownstory
