### ISSUE TITLE
Quantile Regression Beyond Pinball Loss

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#1102]
**Prerequisites**

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your issue might need further discussing before being defined as a feature request:
      Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Is your feature request related to a problem? Please describe.**

QR with pinball loss may limit the output of desired prediction intervals in terms of _calibration_, _sharpness_, and _centered intervals_. See [whitepaper](https://arxiv.org/abs/2011.09588) for details.

**Describe the solution you'd like**

Alternative QR methods from this [whitepaper](https://arxiv.org/abs/2011.09588), including:
1. Model Agnostic QR (MAQR) with conditional density estimation
2. Combined calibration loss to balance calibration and sharpness
3. Interval score for centered intervals
4. Group batching method to induce adversarial group

**Describe alternatives you've considered**

The alternative uses the _naive_ or absolute residual conformal prediction method. However, another conformal prediction method called Conformalized Quantile Regression (CQR) can complement this modified QR, as it creates conformal predictive intervals on top of any existing QR. In fact, CQR can be a way to empirically evaluate the performance of the underlying QRs.

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
