### ISSUE TITLE
[Inclusion of Neural Prophet in Darts] relaxing dependencies

### ISSUE THREAD

**Issue by hrzn** [ourownstory/neural_prophet#1129]
Hi team, @ourownstory, 
We are considering introducing Neural Prophet in Darts (see: https://github.com/unit8co/darts/pull/1436). Unfortunately the current requirements are a bit too strict for us. Both pytorch lightning and torchmetrics versions are currently pinned. I made a quick test and it seems your unit tests are running fine with Pytorch lightning 1.9.0. Would it be possible to consider relaxing the dependencies (at least with `>=`, and if possible with older lower bounds)? That could maybe also benefit some of your users.

Cheers,
Julien

**Comment by karl-richter** [comment]
Hi Julien, thanks so much for considering the integration of NP into Darts.
I'm looking into the dependencies rn, we can definitely loosen them by a lot! At some point we ran into troubles with a certain version, but that should be fixed now. You can track the progress in #1145.

Best, Karl

**Comment by karl-richter** [comment]
@hrzn, we adjusted the dependencies after some evaluations of the newer package versions. Hope that helps. Let me know if you notice any further roadblocks.

**Comment by hrzn** [comment]
Very nice, looks great, thanks @karl-richter !
