### ISSUE TITLE
plotly figures do not show in colab notebooks

### ISSUE THREAD

**Issue by LeonieFreisinger** [ourownstory/neural_prophet#1165]
**Description**

Currently figures are not displayed at all in google colab notebooks, when using the plotly backend. You can see this problem, when running [this notebook] in (https://github.com/ourownstory/neural_prophet/blob/main/tutorials/feature-use/plotly.ipynb) colab. 
Colab introduced the following fix for this problem, see [this discussion](https://github.com/googlecolab/colabtools/issues/498): 

```
from google.colab import output
output.enable_custom_widget_manager()
```

**Required action**
Check for all NeuralProphet tutorial notebooks if the `plotly` `plotting_backend` is used and import the introduced fix to display the figures properly.

**Comment by SimonWittner** [comment]
Hey, can I work on this?

**Comment by LeonieFreisinger** [comment]
@SimonWittner Thanks for picking that one up. Let me know if you have any questions.

**Comment by SimonWittner** [comment]
@LeonieFreisinger the plotly plots now also work in colab notebooks without any changes. 
Plots with the "plotly-resampler" backend do not work in colab.

**Comment by vijaybirju** [comment]
It is has been 3 weeks already passed. can I make PR. it just takes my few minutes

**Comment by leoniewgnr** [comment]
@SimonWittner are you still working on this because if not @vijaybirju could take over

**Comment by vijaybirju** [comment]
> It was unclear to me, whether this issue is still up-to-date since bigger changes regarding the plotting-backend are planned. I checked with @LeonieFreisinger and will fix this issue.

Simon i am making pull request

**Comment by LeonieFreisinger** [comment]
@vijaybirju Thanks for your interest! Since @SimonWittner is still assigned to the issue, let´s have him continue on the issue. 
@vijaybirju In case you are looking for a good first issue, how about you take over #1258 ?

**Comment by vijaybirju** [comment]
> @vijaybirju Thanks for your interest! Since @SimonWittner is still assigned to the issue, let´s have him continue on the issue. @vijaybirju In case you are looking for a good first issue, how about you take over #1258 ?

sorry it was my bad I  thought he different person from Assignees.

**Comment by vijaybirju** [comment]
> It was unclear to me, whether this issue is still up-to-date since bigger changes regarding the plotting-backend are planned. I checked with @LeonieFreisinger and will fix this issue.

sorry, Simon

**Comment by leoniewgnr** [comment]
closed as handled in https://github.com/ourownstory/neural_prophet/pull/1309
