### ISSUE TITLE
Weekly model gives keyerror with n_lags as any value apart from zero. I have checked the data again and again. The data has two columns ds and y, with ds at intervals of 7. 

### ISSUE THREAD

**Issue by induszing** [ourownstory/neural_prophet#1196]
Weekly model gives keyerror with n_lags as any value apart from zero. I have checked the data again and again. The data has two columns ds and y, with ds at intervals of 7. 

As soon as I make the n_lags as anything apart from 0 it throws keyerror with the number following the error as - (n_lags+1). eg. with 2 lags it shows 'keyerror: -3'

This works:
model = NeuralProphet(ar_reg= 0.7934361336961427, 
                      epochs = 85, 
                      n_changepoints = 6,
                      n_forecasts = 1,
                      n_lags = 0,
                      newer_samples_weight = 1.9904358714888586,
                      num_hidden_layers = 1,
                      seasonality_mode = 'multiplicative',
                      seasonality_reg = 0.5555713216476855,
                      trend_reg = 0.6638046386458363)
                      
This does not:
model = NeuralProphet(ar_reg= 0.7934361336961427, 
                      epochs = 85, 
                      n_changepoints = 6,
                      n_forecasts = 1,
                      n_lags = 1,
                      newer_samples_weight = 1.9904358714888586,
                      num_hidden_layers = 1,
                      seasonality_mode = 'multiplicative',
                      seasonality_reg = 0.5555713216476855,
                      trend_reg = 0.6638046386458363)

**Comment by judussoari** [comment]
Hi @induszing thanks for creating the Issue! Interestingly, my code runs without throwing an Error, using both of your model configs. Can you please
- Tell me what version of NP you are using (I recommend to use the most updated one, by installing with `pip install git+https://github.com/ourownstory/neural_prophet.git`)
- Provide me with a description of your dataset (I created a weekly-freq dataset by myself but maybe yours looks totally different). 

Thanks!

**Comment by judussoari** [comment]
Hi @induszing just checking in again to see whether the error still occurs

**Comment by induszing** [comment]
It worked later but I think the issue was how I was feeding data. I did not find any clear documentation on how to create weekly models or what format input is expected.
