### ISSUE TITLE
drop() got multiple values for argument 'axis'

### ISSUE THREAD

**Issue by kzaho** [ourownstory/neural_prophet#1227]
### Discussed in https://github.com/ourownstory/neural_prophet/discussions/1220

<div type='discussions-op-text'>

<sup>Originally posted by **kzaho** March 16, 2023</sup>
F-n check_dataframe at (https://github.com/ourownstory/neural_prophet/blob/main/neuralprophet/df_utils.py) fails.
Is there an extra star symbol, which should be deleted?
```
regressors_to_remove = list(set(regressors_to_remove))
checked_df = checked_df.drop(*regressors_to_remove, axis=1)
```

**Comment by noxan** [comment]
@kzaho thanks for reporting this. do you have a sample for us to reproduce the error?

**Comment by kzaho** [comment]
Let's pretend that we work with such data:
`{'ds': {0: Timestamp('2022-10-16 00:00:00'),
  1: Timestamp('2022-10-17 00:00:00'),
  2: Timestamp('2022-10-18 00:00:00'),
  3: Timestamp('2022-10-19 00:00:00'),
  4: Timestamp('2022-10-20 00:00:00'),
  5: Timestamp('2022-10-21 00:00:00'),
  6: Timestamp('2022-10-22 00:00:00'),
  7: Timestamp('2022-10-23 00:00:00'),
  8: Timestamp('2022-10-24 00:00:00'),
  9: Timestamp('2022-10-25 00:00:00')},
 'y': {0: 17, 1: 18, 2: 10, 3: 11, 4: 5, 5: 12, 6: 7, 7: 20, 8: 25, 9: 10},
 'price': {0: 3.5,
  1: 3.5,
  2: 3.5,
  3: 3.5,
  4: 3.5,
  5: 3.5,
  6: 3.5,
  7: 3.5,
  8: 3.5,
  9: 3.5},
 'cost': {0: 2.5,
  1: 2.5,
  2: 2.5,
  3: 2.5,
  4: 2.5,
  5: 2.5,
  6: 2.5,
  7: 2.5,
  8: 2.5,
  9: 2.5}}`

I come up with a temporary solution, to explain how it works - we have to review a couple of things:

1st, 'neuralprophet/forecaster.py' - line 2979, "df = df[-(self.max_lags + n_historic_predictions) :]"
so, in case we have trained model with max_lags = 3 and n_historic_predictions = 0,
we will have df with 3 obs.
`{'ds': {0: Timestamp('2022-10-23 00:00:00'),
  1: Timestamp('2022-10-24 00:00:00'),
  2: Timestamp('2022-10-25 00:00:00')},
 'y': {0: 20, 1: 25, 2: 10},
 'price': {0: 3.5, 1: 3.5, 2: 3.5},
 'cost': {0: 2.5, 1: 2.5, 2: 2.5}}`

2nd, this df with 3 obs, would be analyzed and at the line 542 'neuralprophet/df_utils.py'.
In case, our columns ('price' and 'cost') would consist of 1 unique value, these columns would be
appended to 'regressors_to_remove' list. Which leads to the error.

Solution (temporary): slightly modify the last value for both columns ('price' and 'cost').
As, we have fixed data structure with column`s names ['ds', 'y', 'price', 'cost'], we can put index '2:'.
`df.iloc[-1:, 2:] = df.iloc[-1:, 2:]*1.0001`

**Comment by leoniewgnr** [comment]
@noxan are you working on this?

**Comment by noxan** [comment]
@leoniewgnr @kzaho I've submitted a pull request as proposed by you @kzaho, many thanks for the hint. I still receive a "list index out of range" error with the adjusted code, could you please double check?

I've also attached a jupyter notebook with my test code so we can discuss the problem with the same example code. It is all based on your example @kzaho, many thanks!

[issue-1227.ipynb.zip](https://github.com/ourownstory/neural_prophet/files/11181668/issue-1227.ipynb.zip)

**Comment by noxan** [comment]
@Pushkaran-P It does not make any difference for fitting the model, you're all good - only the logging message is misleading.

**Comment by judussoari** [comment]
Hi @kzaho @noxan @leoniewgnr,
NeuralProphet generally does not allow a column that is used as a future regressor and filled with unique values (only exception: the df consists of multiple time series and one time series uses future regressors with only unique values). 
We call a column of unique values that is used as model input `Static Covariates`, which is a component we are currently adding to the framework. 

With that being said, the error message definitely is misleading. I will add a PR that removes the future regressors in a clean way, so that the code runs through without an error (and without using regressors).
