### ISSUE TITLE
cross-validation demo error

### ISSUE THREAD

**Issue by CrazyBalthazar** [ourownstory/neural_prophet#1234]
When I was studying the cross-validation page in the official document, I found that the following code would report an error, prompting "['SmoothL1Loss'] not in index". The output of the test metrics does not include these items. Is it because the version update has been modified?
```
metrics_train = pd.DataFrame(columns=METRICS)
metrics_test = pd.DataFrame(columns=METRICS)

for df_train, df_test in folds:
    m = NeuralProphet(**params)
    train = m.fit(df=df_train, freq="MS")
    test = m.test(df=df_test)
    metrics_train = metrics_train.append(train[METRICS].iloc[-1])
    metrics_test = metrics_test.append(test[METRICS].iloc[-1]
```
test metrics like this
![image](https://user-images.githubusercontent.com/43956952/227927644-973bec3d-3695-44d4-a1f2-0b1a7667801f.png)

**Comment by noxan** [comment]
@CrazyBalthazar thanks for reporting the issue, I can confirm it. we'll get back to you with a fix.

**Comment by noxan** [comment]
@karl-richter seems the return values of the metrics in our `test` function changed with the lightning migration. do you have any idea how to retrieve the prior metrics for `test` calls?

**Comment by leoniewgnr** [comment]
Hi, we are planning to include this in our V1 release in three weeks, but have no capacity work on this. If someone want to take over this issue, you are welcome to do so

**Comment by judussoari** [comment]
@CrazyBalthazar we addressed the Issue. Thanks for reporting this.
