### ISSUE TITLE
Add plotly-static plotting backend

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#1235]
**Is your feature request related to a problem? Please describe.**

- The plots in the tutorial Jupyter notebooks cannot be saved and restored due the interactive nature of plotly plots.

**Describe the solution you'd like**

- Add a `plotly-static` option for our plotting backend which renders static (non-interactive) plotly plots.

**Alternatives considered**

- It would be possible to set the plotting backend to `plotly` (without the resampler), capture the returned figure and override the renderer, e.g. `fig.show(renderer="svg")`. But this is rather unpractical if users want to opt for the interactive version when they work through the tutorials and have to adjust this each and every time.

**Comment by hxyue1** [comment]
I can work on this
