### ISSUE TITLE
Installing NeuralProphet in Google Colab Notebook: `ERROR` in pip's dependency resolver

### ISSUE THREAD

**Issue by kyle-w-brown** [ourownstory/neural_prophet#1249]
## Environment Details

NeuralProphet version: 0.5.3 (latest)
Python version: 3.9 (Colab Notebook)
Operating System: Linux (Colab Notebook)

## Error Description

When running `!pip install neuralprophet[live]` in Colab Notebook, I'm receiving the following error:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.15.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchtext 0.15.1 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchdata 0.6.0 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
torchaudio 2.0.1+cu118 requires torch==2.0.0, but you have torch 1.13.1 which is incompatible.
```

NeuralProphet does not run and breaks runtime.

**Comment by jsedoc** [comment]
I had a similar problem. Did you try changing the batch_size?

**Comment by jsedoc** [comment]
To be clear, I think (but I may be incorrect) there are two problems. 1) dependency issues, 2) the auto batch_size calculation.  If I change the batch_size then everything works.

**Comment by kyle-w-brown** [comment]
It restarts runtime regardless of batch_size.

**Comment by leoniewgnr** [comment]
I can confirm the error (macOS), thanks for raising this, we will have a look!

**Comment by jsedoc** [comment]
I noticed that if I change the instance type to GPU and also make the proper updates

```
!pip install -q -U torchvision==0.14.1 torchaudio==0.13.1 torchtext==0.14.1 torchdata==0.5.1
!pip install -q neuralprophet
```

then everything works.

**Comment by leoniewgnr** [comment]
@kyle-w-brown does this also work for you?
then I would close the issue, let me know if you have any more questions:)

**Comment by kyle-w-brown** [comment]
@leoniewgnr Yes, it works for me. Thank you for the help :)
Thank you as well @jsedoc.

**Comment by leoniewgnr** [comment]
Perfect, all the best!
