### ISSUE TITLE
Plotting AirPassenger Forecast (data before 1970) fails for default plotting_backend - time.localtime() error

### ISSUE THREAD

**Issue by hxyue1** [ourownstory/neural_prophet#1258]
**Prerequisites**

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

`fig = m.plot(forecast)` from the test and cross validate tutorial fails to run in a jupyter notebook but runs fine in a python script. I'm also running on Windows so I'm not sure how that plays into it.

**To Reproduce**

Run the code in [tutorial](https://neuralprophet.com/notebooks/test_and_crossvalidate.html) in a jupyter notebook up to cell 4. Then run the same code in a python script.

**Expected behavior**

For both methods to work and produce the same plot.

**What actually happens**

The code run in the jupyter notebook errors, but the code run in a python script works.

**Screenshots**
![image](https://user-images.githubusercontent.com/42855604/231556787-e33f2af1-ff0f-4db3-94ef-3a57493e7112.png)
![image](https://user-images.githubusercontent.com/42855604/231556810-34aee150-6ea1-4728-aa5e-de228451b61b.png)

Full stack trace from the Jupyter notebook:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[3], line 5
      3 future = m.make_future_dataframe(df, periods=24, n_historic_predictions=48)
      4 forecast = m.predict(future)
----> 5 fig = m.plot(forecast)

File ~\Work\neural_prophet\neuralprophet\forecaster.py:1789, in NeuralProphet.plot(self, fcst, df_name, ax, xlabel, ylabel, figsize, forecast_in_focus, plotting_backend)
   1787 log_warning_deprecation_plotly(plotting_backend)
   1788 if plotting_backend.startswith("plotly"):
-> 1789     return plot_plotly(
   1790         fcst=fcst,
   1791         quantiles=self.config_train.quantiles,
   1792         xlabel=xlabel,
   1793         ylabel=ylabel,
   1794         figsize=tuple(x * 70 for x in figsize),
   1795         highlight_forecast=forecast_in_focus,
   1796         resampler_active=plotting_backend == "plotly-resampler",
   1797     )
   1798 else:
   1799     return plot(
   1800         fcst=fcst,
   1801         quantiles=self.config_train.quantiles,
   (...)
   1806         highlight_forecast=forecast_in_focus,
   1807     )

File ~\Work\neural_prophet\neuralprophet\plot_forecast_plotly.py:228, in plot(fcst, quantiles, xlabel, ylabel, highlight_forecast, line_per_origin, figsize, resampler_active)
    192 # Plot trend
    193 # if trend:
    194 #    data.append(
   (...)
    201 #        )
    202 #    )
    204 layout = go.Layout(
    205     showlegend=True,
    206     width=figsize[0],
   (...)
    226     **layout_args,
    227 )
--> 228 fig = go.Figure(data=data, layout=layout)
    229 return fig

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly_resampler\registering.py:76, in _register_wrapper.<locals>.wrapped_constr(*args, **kwargs)
     73 @wraps(constr)
     74 def wrapped_constr(*args, **kwargs):
     75     # print(f"Executing constructor wrapper for {constr_name}", constr)
---> 76     return pr_class(constr(*args, **kwargs), **aggregator_kwargs)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly_resampler\figure_resampler\figurewidget_resampler.py:67, in FigureWidgetResampler.__init__(self, figure, convert_existing_traces, default_n_shown_samples, default_downsampler, resampled_trace_prefix_suffix, show_mean_aggregation_size, convert_traces_kwargs, verbose)
     65     f._grid_str = figure._grid_str
     66     f._grid_ref = figure._grid_ref
---> 67     f.add_traces(figure.data)
     68 elif isinstance(figure, dict) and (
     69     "data" in figure or "layout" in figure  # or "frames" in figure  # TODO
     70 ):
     71     # A figure as a dict, can be;
     72     # - a plotly figure as a dict (after calling `fig.to_dict()`)
     73     # - a pickled (plotly-resampler) figure (after loading a pickled figure)
     74     f.layout = figure.get("layout")

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly\graph_objs\_figurewidget.py:982, in FigureWidget.add_traces(self, data, rows, cols, secondary_ys, exclude_empty_subplots)
    906 def add_traces(
    907     self,
    908     data,
   (...)
    912     exclude_empty_subplots=False,
    913 ) -> "FigureWidget":
    914     """
    915 
    916     Add traces to the figure
   (...)
    980 
    981     """
--> 982     return super(FigureWidget, self).add_traces(
    983         data, rows, cols, secondary_ys, exclude_empty_subplots
    984     )

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly\basedatatypes.py:2246, in BaseFigure.add_traces(self, data, rows, cols, secondary_ys, exclude_empty_subplots)
   2243 self._data_objs = self._data_objs + data
   2245 # Update messages
-> 2246 self._send_addTraces_msg(new_traces_data)
   2248 return self

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly\basewidget.py:273, in BaseFigureWidget._send_addTraces_msg(self, new_traces_data)
    265 add_traces_msg = {
    266     "trace_data": new_traces_data,
    267     "trace_edit_id": trace_edit_id,
    268     "layout_edit_id": layout_edit_id,
    269 }
    271 # Send message
    272 # ------------
--> 273 self._py2js_addTraces = add_traces_msg
    274 self._py2js_addTraces = None

File ~\anaconda3\envs\np_issue_2\lib\site-packages\plotly\basedatatypes.py:719, in BaseFigure.__setattr__(self, prop, value)
    706 """
    707 Parameters
    708 ----------
   (...)
    715 None
    716 """
    717 if prop.startswith("_") or hasattr(self, prop):
    718     # Let known properties and private properties through
--> 719     super(BaseFigure, self).__setattr__(prop, value)
    720 else:
    721     # Raise error on unknown public properties
    722     raise AttributeError(prop)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\traitlets\traitlets.py:732, in TraitType.__set__(self, obj, value)
    730     raise TraitError('The "%s" trait is read-only.' % self.name)
    731 else:
--> 732     self.set(obj, value)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\traitlets\traitlets.py:721, in TraitType.set(self, obj, value)
    717     silent = False
    718 if silent is not True:
    719     # we explicitly compare silent to True just in case the equality
    720     # comparison above returns something other than True/False
--> 721     obj._notify_trait(self.name, old_value, new_value)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\traitlets\traitlets.py:1505, in HasTraits._notify_trait(self, name, old_value, new_value)
   1504 def _notify_trait(self, name, old_value, new_value):
-> 1505     self.notify_change(
   1506         Bunch(
   1507             name=name,
   1508             old=old_value,
   1509             new=new_value,
   1510             owner=self,
   1511             type="change",
   1512         )
   1513     )

File ~\anaconda3\envs\np_issue_2\lib\site-packages\ipywidgets\widgets\widget.py:700, in Widget.notify_change(self, change)
    696 if self.comm is not None and getattr(self.comm, 'kernel', True) is not None:
    697     # Make sure this isn't information that the front-end just sent us.
    698     if name in self.keys and self._should_send_property(name, getattr(self, name)):
    699         # Send new state to front-end
--> 700         self.send_state(key=name)
    701 super().notify_change(change)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\ipywidgets\widgets\widget.py:586, in Widget.send_state(self, key)
    584 state, buffer_paths, buffers = _remove_buffers(state)
    585 msg = {'method': 'update', 'state': state, 'buffer_paths': buffer_paths}
--> 586 self._send(msg, buffers=buffers)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\ipywidgets\widgets\widget.py:825, in Widget._send(self, msg, buffers)
    823 """Sends a message to the model in the front-end."""
    824 if self.comm is not None and (self.comm.kernel is not None if hasattr(self.comm, "kernel") else True):
--> 825     self.comm.send(data=msg, buffers=buffers)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\comm\base_comm.py:113, in BaseComm.send(self, data, metadata, buffers)
    111 def send(self, data=None, metadata=None, buffers=None):
    112     """Send a message to the frontend-side version of this comm"""
--> 113     self.publish_msg(
    114         "comm_msg",
    115         data=data,
    116         metadata=metadata,
    117         buffers=buffers,
    118     )

File ~\anaconda3\envs\np_issue_2\lib\site-packages\ipykernel\comm\comm.py:36, in BaseComm.publish_msg(self, msg_type, data, metadata, buffers, **keys)
     33 if self.kernel is None:
     34     self.kernel = Kernel.instance()
---> 36 self.kernel.session.send(
     37     self.kernel.iopub_socket,
     38     msg_type,
     39     content,
     40     metadata=json_clean(metadata),
     41     parent=self.kernel.get_parent("shell"),
     42     ident=self.topic,
     43     buffers=buffers,
     44 )

File ~\anaconda3\envs\np_issue_2\lib\site-packages\jupyter_client\session.py:850, in Session.send(self, stream, msg_or_type, content, parent, ident, buffers, track, header, metadata)
    848 if self.adapt_version:
    849     msg = adapt(msg, self.adapt_version)
--> 850 to_send = self.serialize(msg, ident)
    851 to_send.extend(buffers)
    852 longest = max([len(s) for s in to_send])

File ~\anaconda3\envs\np_issue_2\lib\site-packages\jupyter_client\session.py:719, in Session.serialize(self, msg, ident)
    717     content = self.none
    718 elif isinstance(content, dict):
--> 719     content = self.pack(content)
    720 elif isinstance(content, bytes):
    721     # content is already packed, as in a relayed message
    722     pass

File ~\anaconda3\envs\np_issue_2\lib\site-packages\jupyter_client\session.py:95, in json_packer(obj)
     93 """Convert a json object to a bytes."""
     94 try:
---> 95     return json.dumps(
     96         obj,
     97         default=json_default,
     98         ensure_ascii=False,
     99         allow_nan=False,
    100     ).encode("utf8", errors="surrogateescape")
    101 except (TypeError, ValueError) as e:
    102     # Fallback to trying to clean the json before serializing
    103     packed = json.dumps(
    104         json_clean(obj),
    105         default=json_default,
    106         ensure_ascii=False,
    107         allow_nan=False,
    108     ).encode("utf8", errors="surrogateescape")

File ~\anaconda3\envs\np_issue_2\lib\json\__init__.py:234, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    232 if cls is None:
    233     cls = JSONEncoder
--> 234 return cls(
    235     skipkeys=skipkeys, ensure_ascii=ensure_ascii,
    236     check_circular=check_circular, allow_nan=allow_nan, indent=indent,
    237     separators=separators, default=default, sort_keys=sort_keys,
    238     **kw).encode(obj)

File ~\anaconda3\envs\np_issue_2\lib\json\encoder.py:199, in JSONEncoder.encode(self, o)
    195         return encode_basestring(o)
    196 # This doesn't pass the iterator directly to ''.join() because the
    197 # exceptions aren't as detailed.  The list call should be roughly
    198 # equivalent to the PySequence_Fast that ''.join() would do.
--> 199 chunks = self.iterencode(o, _one_shot=True)
    200 if not isinstance(chunks, (list, tuple)):
    201     chunks = list(chunks)

File ~\anaconda3\envs\np_issue_2\lib\json\encoder.py:257, in JSONEncoder.iterencode(self, o, _one_shot)
    252 else:
    253     _iterencode = _make_iterencode(
    254         markers, self.default, _encoder, self.indent, floatstr,
    255         self.key_separator, self.item_separator, self.sort_keys,
    256         self.skipkeys, _one_shot)
--> 257 return _iterencode(o, 0)

File ~\anaconda3\envs\np_issue_2\lib\site-packages\jupyter_client\jsonutil.py:111, in json_default(obj)
    109 if isinstance(obj, datetime):
    110     obj = _ensure_tzinfo(obj)
--> 111     return obj.isoformat().replace('+00:00', 'Z')
    113 if isinstance(obj, bytes):
    114     return b2a_base64(obj, newline=False).decode('ascii')

File ~\anaconda3\envs\np_issue_2\lib\site-packages\dateutil\tz\tz.py:222, in tzlocal.utcoffset(self, dt)
    219 if dt is None and self._hasdst:
    220     return None
--> 222 if self._isdst(dt):
    223     return self._dst_offset
    224 else:

File ~\anaconda3\envs\np_issue_2\lib\site-packages\dateutil\tz\tz.py:291, in tzlocal._isdst(self, dt, fold_naive)
    288     return False
    290 # Check for ambiguous times:
--> 291 dstval = self._naive_is_dst(dt)
    292 fold = getattr(dt, 'fold', None)
    294 if self.is_ambiguous(dt):

File ~\anaconda3\envs\np_issue_2\lib\site-packages\dateutil\tz\tz.py:260, in tzlocal._naive_is_dst(self, dt)
    258 def _naive_is_dst(self, dt):
    259     timestamp = _datetime_to_timestamp(dt)
--> 260     return time.localtime(timestamp + time.timezone).tm_isdst

OSError: [Errno 22] Invalid argument

**Environment (please complete the following information):**

 - Python 3.9
 - NeuralProphet 0.5.3

**Additional context**

I'm running on Windows so I'm not sure how that might complicate things.

**Comment by LeonieFreisinger** [comment]
@hxyue1 The problem occurs do to the fact that the time package considers the localtime only for the years after 1970. Hence, a fix needs to be implemented to circumvent the error. 
Check out this link: https://stackoverflow.com/questions/16387787/odd-behaviour-of-ephems-python-package-localtime-function

**Comment by LeonieFreisinger** [comment]
@vijaybirju Feel free to comment here, in case you would like to work on this issue.

**Comment by ourownstory** [comment]
Closing this as the issue comes from upstream dependencies is specific to Windows and can be circumvented by using WSL.
