### ISSUE TITLE
Enhance Additive Nested Moodel

### ISSUE THREAD

**Issue by LeonieFreisinger** [ourownstory/neural_prophet#1296]
** Status Quo** 
Currently, the additive nested model is implemented in a 2-step forward pass:
https://github.com/ourownstory/neural_prophet/blob/main/neuralprophet/time_net.py#L621-L626
This requires the tabularized targets of size `n_lags `and the tabularized targets of size `n_forecast `to be tabularized separately.
Since this is approach is computationally heavy, we would like to optimize the tabularization and forward procedure.

** Required Changes ** 
Ideas:
- tabularize each component on one go --> size = (`n_lags `+ `n_forecast`)
- only have one call of each component's function in the forward pass. 

Consider case of no trend and seasonality

**Comment by ourownstory** [comment]
This has been implemented in 0.7.0
