### ISSUE TITLE
events/holidays regularization does not reduce weights to zero.

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#133]

**Comment by noxan** [comment]
Happy to help contribute to this issue as discussed.

I've traced down the implementation to these functions:
1) https://github.com/ourownstory/neural_prophet/blob/bae43ab9f934eee81d79fb773ae2852604b81a54/neuralprophet/forecaster.py#L2025-L2028
2) https://github.com/ourownstory/neural_prophet/blob/bae43ab9f934eee81d79fb773ae2852604b81a54/neuralprophet/utils.py#L58

Documentation is currently lacking in NeuralProphet, the [documentation from Prophet](https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#prior-scale-for-holidays-and-seasonality) seems helpful.

To experiment with the effect of regularization on events/holidays, I've created the following scripts, including first results attached:
1) [Event regularization sample](https://github.com/noxan/neural_prophet/blob/issue-133/untitled-01.py), here without regularization the event weight is `OrderedDict([('birthday_+0', tensor(0.2050, grad_fn=<SelectBackward0>))])`, while for `regularization=1` it is reduced to `OrderedDict([('birthday_+0', tensor(6.3685e-07, grad_fn=<SelectBackward0>))])`
2) [Holiday regularization sample](https://github.com/noxan/neural_prophet/blob/issue-133/Untitled-1.ipynb), including [results for different regularization parameters](https://github.com/noxan/neural_prophet/blob/issue-133/regularization-results.txt)
