### ISSUE TITLE
pip install issue

### ISSUE THREAD

**Issue by ale-dg** [ourownstory/neural_prophet#1339]
Hi,

Hope everything is going well. I have been trying to install the package through pip and it becomes stuck when trying to build the wheel. It loops over some versions of pandas, even though I have the newest one (2.0.1). Below the entire process until I stopped it. Is this normal or should I wait until the newer version is released? 

Thanks

Best,

  Collecting neuralprophet
    Using cached neuralprophet-0.5.4-py3-none-any.whl (128 kB)
  Collecting captum>=0.5.0 (from neuralprophet)
    Using cached captum-0.6.0-py3-none-any.whl (1.3 MB)
  Requirement already satisfied: convertdate>=2.1.2 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (2.4.0)
  Requirement already satisfied: holidays>=0.20 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (0.25)
  Requirement already satisfied: ipywidgets>=7.5.1 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (8.0.6)
  Requirement already satisfied: LunarCalendar>=0.0.9 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (0.0.9)
  Requirement already satisfied: matplotlib>=2.0.0 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (3.7.1)
  Collecting numpy<1.24.0,>=1.15.4 (from neuralprophet)
    Using cached numpy-1.23.5-cp311-cp311-macosx_11_0_arm64.whl (13.3 MB)
  Requirement already satisfied: pandas>=1.0.4 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (2.0.1)
  Requirement already satisfied: plotly>=5.12.0 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (5.14.1)
  Collecting dash<2.9 (from neuralprophet)
    Using cached dash-2.8.1-py3-none-any.whl (9.9 MB)
  Collecting plotly-resampler>=0.8.3 (from neuralprophet)
    Using cached plotly_resampler-0.8.3.2.tar.gz (46 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
  Requirement already satisfied: python-dateutil>=2.8.0 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (2.8.2)
  Collecting pytorch-lightning<2.0.0,>=1.7 (from neuralprophet)
    Using cached pytorch_lightning-1.9.5-py3-none-any.whl (829 kB)
  Collecting tensorboard (from neuralprophet)
    Using cached tensorboard-2.13.0-py3-none-any.whl (5.6 MB)
  INFO: pip is looking at multiple versions of neuralprophet to determine which version is compatible with other requirements. This could take a while.
  Collecting neuralprophet
    Using cached neuralprophet-0.5.3-py3-none-any.whl (132 kB)
    Using cached neuralprophet-0.5.2-py3-none-any.whl (146 kB)
  Requirement already satisfied: pytorch-lightning>=1.7 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (2.0.2)
  Requirement already satisfied: torch>=1.8.0 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (2.0.1)
  Requirement already satisfied: torchmetrics>=0.9.3 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (0.11.4)
  Requirement already satisfied: widgetsnbextension>=4.0.5 in ./ts_test_env/lib/python3.11/site-packages (from neuralprophet) (4.0.7)
  Requirement already satisfied: pymeeus<=1,>=0.3.13 in ./ts_test_env/lib/python3.11/site-packages (from convertdate>=2.1.2->neuralprophet) (0.5.12)
  Requirement already satisfied: korean-lunar-calendar in ./ts_test_env/lib/python3.11/site-packages (from holidays>=0.20->neuralprophet) (0.3.1)
  Requirement already satisfied: ipykernel>=4.5.1 in ./ts_test_env/lib/python3.11/site-packages (from ipywidgets>=7.5.1->neuralprophet) (6.23.1)
  Requirement already satisfied: ipython>=6.1.0 in ./ts_test_env/lib/python3.11/site-packages (from ipywidgets>=7.5.1->neuralprophet) (8.13.2)
  Requirement already satisfied: traitlets>=4.3.1 in ./ts_test_env/lib/python3.11/site-packages (from ipywidgets>=7.5.1->neuralprophet) (5.9.0)
  Requirement already satisfied: jupyterlab-widgets~=3.0.7 in ./ts_test_env/lib/python3.11/site-packages (from ipywidgets>=7.5.1->neuralprophet) (3.0.7)
  Requirement already satisfied: ephem>=3.7.5.3 in ./ts_test_env/lib/python3.11/site-packages (from LunarCalendar>=0.0.9->neuralprophet) (4.1.4)
  Requirement already satisfied: pytz in ./ts_test_env/lib/python3.11/site-packages (from LunarCalendar>=0.0.9->neuralprophet) (2023.3)
  Requirement already satisfied: contourpy>=1.0.1 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (1.0.7)
  Requirement already satisfied: cycler>=0.10 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (0.11.0)
  Requirement already satisfied: fonttools>=4.22.0 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (4.39.4)
  Requirement already satisfied: kiwisolver>=1.0.1 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (1.4.4)
  Requirement already satisfied: packaging>=20.0 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (23.1)
  Requirement already satisfied: pillow>=6.2.0 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (9.5.0)
  Requirement already satisfied: pyparsing>=2.3.1 in ./ts_test_env/lib/python3.11/site-packages (from matplotlib>=2.0.0->neuralprophet) (3.0.9)
  Requirement already satisfied: tzdata>=2022.1 in ./ts_test_env/lib/python3.11/site-packages (from pandas>=1.0.4->neuralprophet) (2023.3)
  Requirement already satisfied: tenacity>=6.2.0 in ./ts_test_env/lib/python3.11/site-packages (from plotly>=5.12.0->neuralprophet) (8.2.2)
  Collecting dash<3.0.0,>=2.2.0 (from plotly-resampler>=0.8.3->neuralprophet)
    Using cached dash-2.10.0-py3-none-any.whl (10.3 MB)
  Collecting jupyter-dash>=0.4.2 (from plotly-resampler>=0.8.3->neuralprophet)
    Using cached jupyter_dash-0.4.2-py3-none-any.whl (23 kB)
  INFO: pip is looking at multiple versions of plotly-resampler to determine which version is compatible with other requirements. This could take a while.
  Collecting plotly-resampler>=0.8.3 (from neuralprophet)
    Using cached plotly-resampler-0.8.3.1.tar.gz (68 kB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
  Collecting Flask-Cors<4.0.0,>=3.0.10 (from plotly-resampler>=0.8.3->neuralprophet)
    Using cached Flask_Cors-3.0.10-py2.py3-none-any.whl (14 kB)
  Collecting Werkzeug<=2.1.2 (from plotly-resampler>=0.8.3->neuralprophet)
    Using cached Werkzeug-2.1.2-py3-none-any.whl (224 kB)
  Collecting pandas>=1.0.4 (from neuralprophet)
    Using cached pandas-2.0.1-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
    Using cached pandas-2.0.0-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
    Using cached pandas-1.5.3-cp311-cp311-macosx_11_0_arm64.whl (10.8 MB)
  INFO: pip is looking at multiple versions of plotly-resampler to determine which version is compatible with other requirements. This could take a while.
    Using cached pandas-1.5.2-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
    Using cached pandas-1.5.1-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
    Using cached pandas-1.5.0-cp311-cp311-macosx_11_0_arm64.whl (10.7 MB)
  INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
    Using cached pandas-1.4.4.tar.gz (4.9 MB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Using cached pandas-1.4.3.tar.gz (4.9 MB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Using cached pandas-1.4.2.tar.gz (4.9 MB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Using cached pandas-1.4.1.tar.gz (4.9 MB)
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Downloading pandas-1.4.0.tar.gz (4.9 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 4.3 MB/s eta 0:00:00
    Installing build dependencies ... done
    Getting requirements to build wheel ... done
    Preparing metadata (pyproject.toml) ... done
    Downloading pandas-1.3.5.tar.gz (4.7 MB)
       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 5.7 MB/s eta 0:00:00
    Installing build dependencies ... done
  ^C  Getting requirements to build wheel ... canceled
  ERROR: Operation cancelled by user

**Comment by ale-dg** [comment]
Hi,

Just for the record... I have tried to install it today in a complete new environment... and the issue still happens.

Best

**Comment by leoniewgnr** [comment]
@ale-dg Its totally normal that those packages are downloaded, just let it keep running. If you encounter more difficulties, feel free to join our slack #help channel.
