### ISSUE TITLE
Issue when using m.make_future_dataframe to create a future dataframe. 

### ISSUE THREAD

**Issue by cummins070** [ourownstory/neural_prophet#1340]
Hi there,

I have a simple DF containing just ds and y, spanning the dates 2022-04-09 through 2023-05-29. 
![Screenshot 2023-06-01 103453](https://github.com/ourownstory/neural_prophet/assets/47199409/a6aeee6d-f3ec-4724-9899-58e834aec37d)

When I fit the most basic model and then use:

`df_future = m.make_future_dataframe(df_basic, n_historic_predictions=True, periods=365)`

It works perfectly fine, I get my extended dataframe with the y values showing as 'None'.

However, when using a different model like below:

`# Model and prediction
m = NeuralProphet(
    # Disable trend changepoints
    n_changepoints=10,
    # Disable seasonality components
    yearly_seasonality=True,
    weekly_seasonality=True,
    daily_seasonality=True,
    # Add the autogression
    n_lags=10,
)
m.set_plotting_backend("matplotlib")  # Use matplotlib due to #1235
metrics = m.fit(df_basic)
forecast = m.predict(df_basic)
m.plot(forecast)`

I now try to run the same m.make_future_dataframe code as above, but the resulting dataframe only has 1 additional row added
![image 1](https://github.com/ourownstory/neural_prophet/assets/47199409/c2dae118-50b6-40ac-b15e-218d238d0c6a)

If i set  `n_historic_predictions=False` on the new model, then it only gives 10 total rows, 9 of which are the existing dataframe and 1 is the new row.
![image 2](https://github.com/ourownstory/neural_prophet/assets/47199409/f41ea11d-fc7b-4814-9634-0eae27d1da7e)

Is there any reason for this? My dataframe does not have any gaps between days, I'm really pulling my hair out as to why this is occurring and how to fix. Any advice would be greatly appreciated. I'd like to build a more complex model but the inability to create the future dataframe for prediction is stopping me in my tracks.

**Comment by judussoari** [comment]
Hi @cummins070 , thanks for reaching out! 
When Auto-regression is enabled, you will need to specify `n_forecasts=` in the model configuration. The default of it is 1, and with AR enabled, the default will not be overwritten by the `periods=` parameter. 
Let me know if it helps! 
best, 
Julio

**Comment by pri2si17-1997** [comment]
Hi @leoniewgnr when n_forecasts=300  then the output has `yhat1`, `yhat2` ... `yhat300` for each time step (ds). So which forecast is actual for date like how to interpret the predictions when it has 300 predictions for one date. Please let me know.

**Comment by chenslcool** [comment]
> Hi @leoniewgnr when n_forecasts=300 then the output has `yhat1`, `yhat2` ... `yhat300` for each time step (ds). So which forecast is actual for date like how to interpret the predictions when it has 300 predictions for one date. Please let me know.

do you know now?
