### ISSUE TITLE
Future dataframe when using future regressors

### ISSUE THREAD

**Issue by simonsapiel** [ourownstory/neural_prophet#1342]
Hi! There seems not to be any tutorial on how to run a similar snippet as to 

```python
# Create a new dataframe reaching 365 into the future for our forecast, n_historic_predictions also shows historic data
df_future = m.make_future_dataframe(df, n_historic_predictions=True, periods=365)

# Predict the future
forecast = m.predict(df_future)

# Visualize the forecast
m.plot(forecast)
```
from 01: The basics when using future regressors.

So say I have 

```python
m = NeuralProphet(
    n_changepoints=10,
    yearly_seasonality=True,
    weekly_seasonality=False,
    daily_seasonality=False,
)

m.set_plotting_backend("plotly")

m.add_future_regressor("reg1")
m.add_future_regressor("reg2")

metrics = m.fit(df)
```
then running `df_future = m.make_future_dataframe(df, n_historic_predictions=True, periods=365)` will produce `ValueError: Future values of all user specified regressors not provided`. 

What is the appropriate way to create the future dataframe when you are using future regressors?

**Comment by leoniewgnr** [comment]
If you've trained your model with future regressors, then the model also needs to get those regressors when it should predict into the future. 
So either train your model with lagged regressors or provide future regressors to `make_future_dataframe`.
Hope that helps!
