### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ronamadthis** [ourownstory/neural_prophet#1363]
**Prerequisites**

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**
TypeError with NeuralProphet 

*Python environment is 3.7.6. Using NeuralProphet 0.3.2, Installed from PyPI.
It was working fine until recently. I decided to upgrade it to version 0.5.2 when I got the error. Then I decided to downgrade it back to 0.3.2 to avoid the error with NeuralProphet and now I get the following error also in version 0.3.2.

TypeError                                 Traceback (most recent call last)
<ipython-input-1-9717d38c3e86> in <module>
      2 import numpy as np
      3 from datetime import datetime
----> 4 from neuralprophet import NeuralProphet

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\__init__.py in <module>
     23     warnings_log.addHandler(f_handler)
     24 
---> 25 from .forecaster import NeuralProphet
     26 from .utils import set_random_seed, set_log_level
     27 from .df_utils import split_df

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\forecaster.py in <module>
      9 from tqdm import tqdm
     10 
---> 11 from neuralprophet import configure
     12 from neuralprophet import time_net
     13 from neuralprophet import time_dataset

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\configure.py in <module>
     10 import types
     11 
---> 12 from neuralprophet import utils_torch, utils, df_utils
     13 
     14 log = logging.getLogger("NP.config")

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\utils_torch.py in <module>
      6 from torch_lr_finder import LRFinder
      7 
----> 8 from neuralprophet import utils
      9 
     10 log = logging.getLogger("NP.utils_torch")

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\utils.py in <module>
      6 import torch
      7 from collections import OrderedDict
----> 8 from neuralprophet import hdays as hdays_part2
      9 import holidays as pyholidays
     10 import warnings

~\AppData\Roaming\Python\Python37\site-packages\neuralprophet\hdays.py in <module>
    431 
    432 
--> 433 class TU(Turkey):
    434     pass
    435 

~\AppData\Roaming\Python\Python37\site-packages\holidays\registry.py in __init__(self, path, *args, **kwargs)
    180         if args:
    181             raise TypeError(
--> 182                 "This is a python-holidays entity loader class. "
    183                 "For entity inheritance purposes please import a class you "
    184                 "want to derive from directly: e.g., "

TypeError: This is a python-holidays entity loader class. For entity inheritance purposes please import a class you want to derive from directly: e.g., `from holidays.countries import Entity` or `from holidays.financial import Entity`.

Any help is greatly appreciated.

**Comment by hxyue1** [comment]
Hey can you provide some code to reproduce the issue? Also have you tried installing version 0.6?

**Comment by ronamadthis** [comment]
Hi Hong,

Thank you for getting back to me quickly. I get Type Error before running
any code. I get the error when I load the library in the first cell of
Jupyter Notebook and run it.
I have not installed version0.6.0  as it requires Python 3.8 environment
and I have 3.7.6
It seems to be the holidays moule in NeuralProphet is giving the error.
Appreciate your help.

Ron Martis




<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by hxyue1** [comment]
Hi Ron,

I've confirmed that this is an issue for the versions of python and neuralprophet that you are using. However, this is not an issue in the latest version of neuralprophet so I recommend that you upgrade your Python to 3.8+ so that you can install the latest version of neuralprophet.

**Comment by leoniewgnr** [comment]
If you any more questions, feel free to ask in our slack channel

**Comment by ronamadthis** [comment]
Thanks.
