### ISSUE TITLE
TypeError: Trainer.__init__() got an unexpected keyword argument 'auto_lr_find'

### ISSUE THREAD

**Issue by TanguyLevent** [ourownstory/neural_prophet#1379]
I have this error when I just copy/paste your code and use your dataset. Can't succeed to find how to solve this issue. Could you help?

Thank you so much,

Best,

**Comment by leoniewgnr** [comment]
Hi, which code did you use?

**Comment by TanguyLevent** [comment]
Thank you for your quick answer. 

There is my code:

`from neuralprophet import NeuralProphet, set_log_level

m = NeuralProphet()
m.set_plotting_backend("plotly") 
metrics = m.fit(df_train)
`

my issue comes from the **fit** function.

best

**Comment by leoniewgnr** [comment]
Which NP version are you using?

**Comment by TanguyLevent** [comment]
neuralprophet ==  0.6.2

**Comment by leoniewgnr** [comment]
I recreated you code in NeuralProphet 0.6.2 and everything is fine. Could you please try it in a new virtual environment?
<img width="1780" alt="image" src="https://github.com/ourownstory/neural_prophet/assets/42536262/9d34bd99-f3bb-4cf9-8b33-fe1bad2ea495">

**Comment by leoniewgnr** [comment]
Closed due to inactivity, if you still encounter that problem, feel free to ask on slack
