### ISSUE TITLE
How to configure training with a GPU?

### ISSUE THREAD

**Issue by mturk24** [ourownstory/neural_prophet#138]
Hi there, I was wondering how to fit a neural prophet model assuming there is some GPU setting? (i.e. comparable to the parameter **tree_method='gpu_hist'** for the xgb classifier constructor)

**Comment by HansikaPH** [comment]
Hi, Thanks for your comment. At the moment, NeuralProphet does not have special support for GPUs. We do hope to include this facility soon in an upcoming release.

**Comment by mturk24** [comment]
@HansikaPH Thanks for letting me know appreciate it!

**Comment by ourownstory** [comment]
@mturk24 adding GPU support by itself is simple, and we could simply add it. However, it could be even slower than on CPU as the code is really not optimized for parallel compute. 

To achieve it, the dataloader, model itself and possibly parts of the training loop would have to be re-written. 

It would be a challenging but fun and rewarding project for whoever would like to take it on.
