### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by vibhanshu13** [ourownstory/neural_prophet#1387]
Is there any way to load the model faster currently it is taking 9.5 seconds to load? I am using neural prophet inbuilt save and load functionality.

**Comment by leoniewgnr** [comment]
Hi @vibhanshu13, we are currently working on making NP faster in general. The model loading is also on our list, but will be tackled later as right now we optimize the most important functions like fit. If you want to contribute and make the model loader faster, you are welcome to do so! If you have questions about that, please let me know: https://join.slack.com/t/neuralprophet/shared_invite/zt-1iyfs2pld-vtnegAX4CtYg~6E~V8miXw
