### ISSUE TITLE
NameError: name 'register_plotly_resampler' is not defined

### ISSUE THREAD

**Issue by samialitop3** [ourownstory/neural_prophet#1401]
**Prerequisites**

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

When initializing NeuralProphet, I get this error immediately even before using it.
```
from neuralprophet import NeuralProphet
  File "/usr/local/lib/python3.8/dist-packages/neuralprophet/__init__.py", line 9, in <module>
    from .forecaster import NeuralProphet  # noqa: F401
  File "/usr/local/lib/python3.8/dist-packages/neuralprophet/forecaster.py", line 30, in <module>
    from neuralprophet.plot_forecast_plotly import plot as plot_plotly
  File "/usr/local/lib/python3.8/dist-packages/neuralprophet/plot_forecast_plotly.py", line 6, in <module>
    from neuralprophet.plot_model_parameters_plotly import get_dynamic_axis_range
  File "/usr/local/lib/python3.8/dist-packages/neuralprophet/plot_model_parameters_plotly.py", line 38, in <module>
    register_plotly_resampler(mode="auto")
NameError: name 'register_plotly_resampler' is not defined
```

**To Reproduce**

1. from neuralprophet import NeuralProphet
2. m = NeuralProphet()
3. Got the error after the above line

**Expected behavior**

Expected NeuralProphet to be initialized and work properly.

**What actually happens**

Describe what happens, and how often it happens.

**Screenshots**

If applicable, add screenshots and console printouts to help explain your problem.

**Environement (please complete the following information):**

 - Python environment Python 3.8, in standalone venv with no other packages
 - NeuralProphet version and install method 0.6.2, installed from PYPI with `pip install neuralprophet`

**Additional context**

**Comment by leoniewgnr** [comment]
Hi, I just tried it and it works for me.
What does `pip show plotly` say?

**Comment by samialitop3** [comment]
Hi 

`pip show plotly`
Name: plotly
Version: 5.16.0
Summary: An open-source, interactive data visualization library for Python
Home-page: https://plotly.com/python/
Author: Chris P
Author-email: chris@plot.ly
License: MIT
Location: /Users/administrator/CC/venv/lib/python3.10/site-packages
Requires: packaging, tenacity
Required-by: dash, neuralprophet, plotly-resampler

`pip show plotly-resampler`
Name: plotly-resampler
Version: 0.8.3.2
Summary: Visualizing large time series with plotly
Home-page: https://github.com/predict-idlab/plotly-resampler
Author: Jonas Van Der Donckt
Author-email: 
License: MIT
Location: /Users/administrator/CC/venv/lib/python3.10/site-packages
Requires: dash, jupyter-dash, numpy, orjson, pandas, plotly, trace-updater
Required-by:

**Comment by samialitop3** [comment]
I created a local project and it worked normally, but when I used docker to run the project just to test neural prophet I got the same error 
Here's the repo with the full code
https://github.com/samialitop3/test_neural_prophet_docket

**Comment by samialitop3** [comment]
A quick update here, when I just imported `from plotly_resampler.registering import register_plotly_resampler` I got the following error, which is related to `ipython` library version and its support with the used `python` version, so this should be considered according to the installed python version.
![image](https://github.com/ourownstory/neural_prophet/assets/129103515/dc2fb603-5d8c-4aed-9fe1-c8f5b05d3054)

**Comment by leoniewgnr** [comment]
Thank you so much! This is very interesting!
So what is the solution? Using a newer python version?

**Comment by leoniewgnr** [comment]
Closed due to inactivity

**Comment by samialitop3** [comment]
> Thank you so much! This is very interesting! So what is the solution? Using a newer python version?

Still not sure about the solution because some other python libraries might be depending on a specific version of `ipython` and this might cause conflicts in the installations. 

My main goal is to run both `Prophet` and `Neural Prophet` on the same platform and be able to switch between them for testing neural prophet before agreeing on using it only for prediction.

**Comment by sijie-xiong** [comment]
`pip install --upgrade plotly-resampler` to version 0.9.1 worked for me, somehow neuralprophet's dependency list requries `plotly-resampler<0.9.0.0,>=0.8.3.1` but the function `register_plotly_resampler` only exists in later version of `plotly-resampler`
