### ISSUE TITLE
Add Plotly 

### ISSUE THREAD

**Issue by elieganancia** [ourownstory/neural_prophet#145]
Hi, 

Just like in FbProphet, would it be possible to add a Plotly option to plot_forecast ? Or maybe do you have an other way of doing it ? 

Thanks

**Comment by ourownstory** [comment]
Hi,

Yes, that should be possible. In fact, it makes a great first issue, in case you would like to contribute it? I am happy to support you with it!

Else, it will be added eventually.

**Comment by ourownstory** [comment]
If anyone would like to take it on, you can use this code as inspiration: https://github.com/facebook/prophet/blob/ee592451f2750e780c3e8cbaddab674cff5242a2/python/fbprophet/plot.py#L549

**Comment by victoraccete** [comment]
Hey, @ourownstory. I'm interested in contributing to this issue. This will be my first time ever contributing to an open-source project of this scale. I'll take a look at the inspiration code you gave us and see if I can manage to pull this off.

**Comment by manikTharaka** [comment]
Hi @ourownstory ,

Would like to have a crack at this if it is still open.

Thanks.

**Comment by ourownstory** [comment]
@manikTharaka Wonderful! I'm available to help with any questions you have. Please let me know your email so I can add you to our dev slack. We and the other deva can chat more there. :)

**Comment by manikTharaka** [comment]
Awesome, sent you an email :)
