### ISSUE TITLE
Not able to install the package

### ISSUE THREAD

**Issue by shravankoninti** [ourownstory/neural_prophet#146]
![image](https://user-images.githubusercontent.com/6191291/101023154-5b6b6c80-3598-11eb-8ac6-f6c7e01f1a1f.png)

**Comment by SKVVS** [comment]
first : git clone https://github.com/ourownstory/neural_prophet 
then go to your path: cd your_path/neural_prophet 
and then just run: pip install .[live]

You can do that in windows with anaconda and powershell

**Comment by dmoonat** [comment]
![image](https://user-images.githubusercontent.com/25177773/101043155-003f7700-35a4-11eb-9a07-890fed0b7e55.png)

**Comment by ourownstory** [comment]
@shravankoninti Did @dmoonat's method work for you?

**Comment by jrjarami** [comment]
Not working for me either.

I am getting: 

ERROR: Could not find a version that satisfies the requirement torch<1.7.0,>=1.4.0 (from neuralprophet[live])
ERROR: No matching distribution found for torch<1.7.0,>=1.4.0

**Comment by jrjarami** [comment]
Not working for me either. I am getting:

ERROR: Could not find a version that satisfies the requirement torch<1.7.0,>=1.4.0 (from neuralprophet[live])
ERROR: No matching distribution found for torch<1.7.0,>=1.4.0

**Comment by ourownstory** [comment]
@jrjarami are you also trying to install from a notebook or from a terminal?

You can try installing torch 1.6.0 before installing neuralprophet:
```python
pip install torch==1.6.0
```
or 
```python
pip install torch==1.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
```

Note: I highly recommend using the terminal and installing in a new virtual environment.

**Comment by jrjarami** [comment]
Thanks Oskar,

It worked well. I appreciate your help. Great work creating NeuralProphet...

**Comment by ourownstory** [comment]
Thanks, you're welcome!

**Comment by shravankoninti** [comment]
Thanks All

**Comment by shravankoninti** [comment]
> @shravankoninti Did @dmoonat's method work for you?

Yes
