### ISSUE TITLE
Feature: Adding contributors section to the README.md file.

### ISSUE THREAD

**Issue by Kalyanimhala** [ourownstory/neural_prophet#1471]
There is no Contributors section in readme file .
As we know Contributions are what make the open-source community such an amazing place to learn, inspire, and create.
The Contributors section in a README.md file is important as it acknowledges and gives credit to those who have contributed to a project, fosters community and collaboration, adds transparency and accountability, and helps document the project's history for current and future maintainers. It also serves as a form of recognition, motivating contributors to continue their efforts.
![contributors](https://github.com/ourownstory/neural_prophet/assets/147402107/9a516fed-b1d9-4d96-8fbf-09bdbde60fbe)

**Comment by Kalyanimhala** [comment]
@ourownstory  Kindly assign me this issue, I want to work on it. Thank You!!

**Comment by ourownstory** [comment]
Hi @Kalyanimhala Yes, plese! This has been on the want-list for a while now. 
Please do contribute it, I will merge it!
