### ISSUE TITLE
holidays version conflict with prophet package

### ISSUE THREAD

**Issue by mixcheck** [ourownstory/neural_prophet#1477]
Hi.

I want to use Prophet==1.1.4 and neuralProphet==0.6.2 .

But holidays version confilicts..........

Prophet==1.1.4 has a dependency with holidays>=0.25.

NeuralProphet==0.6.2 has a dependency with holidays <0.22 and holidays>=0.21.

How can I solve?

**Comment by SimonWittner** [comment]
Hi, 
thanks for raising this! I think this issue should be solved with the newest upcoming release.

**Comment by SimonWittner** [comment]
I think this issue should be resolved with the newest version of NeuralProphet 1.0.0rc4. 
You can install the latest version with:
`pip install --pre neuralprophet `
