### ISSUE TITLE
make_future_dataframe needs a zero-based index (document behavior)

### ISSUE THREAD

**Issue by aleave** [ourownstory/neural_prophet#148]
if the input datafarame for the `regressors_df` argument of `make_future_dataframe` has an index not starting from zero, the function will return a NaN filled dataframe.

Assuming the future regressors dataframe is called `future_regressors_df` a simple `future_regressors_df.reset:index(drop=True)` solves the issue for me. This should be in the documentation

**Comment by ourownstory** [comment]
Thank you Alessandro, that was not intended behavior. It should be fixed in the PR. Please check if that solves your original issue, thank you!
