### ISSUE TITLE
Integration with MLflow

### ISSUE THREAD

**Issue by cargecla1** [ourownstory/neural_prophet#1483]
**Prerequisites**

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Answered Questions on the Github Discussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your issue might need further discussing before being defined as a feature request:
      Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Is your feature request related to a problem? Please describe.**

I was trying to use Neuralforecast with MLflow but there wasn't a guide on how to do that. Thus, it will be good to add an example notebook.

**Describe the solution you'd like**

Example code to easily track models, save hyperparameters used for each run and other metadata (e.g. dataset used for the run experiment), compare results and stage models.

**Describe alternatives you've considered**

I have a solution to the MLflow integration via additional code on you notebook/ .py . Could anyone from the team reach me out to let me know where I can add an MLflow notebook example with MLflow integration? Please reach out.

**Additional context**

NIL additional info.

**Comment by SimonWittner** [comment]
Hey @cargecla1,
thanks for bringing this up! This sounds like a great addition to our tutorials. Would you be willing to share your code?

**Comment by cargecla1** [comment]
> Hey @cargecla1, thanks for bringing this up! This sounds like a great addition to our tutorials. Would you be willing to share your code?

Hello @SimonWittner, sure. Please give me a 3-5 few days to share it. 
I noticed that you opened a pull request ([Feature] MLflow tutorial #1487). Are you planning to add it there?

**Comment by SimonWittner** [comment]
Hi @cargecla1 
I am excited to see your code! The code in the tutorial is running. Please feel free to add differences from your code in a PR!

**Comment by cargecla1** [comment]
Hello @SimonWittner,

I added my code as a message on your PR as it seems like I have not write access to push my changes. Not sure why. 

I will post below as well just in case. Good to know that your example code runs as well.

-------------------------------------------------------------------------------------------------------

#### Example with MLflow Autologging

# MLflow setup
# Run this command with environment activated: mlflow ui --port xxxx  (e.g. 5000, 5001, 5002)
# Copy and paste url from command line to web browser

import mlflow
import torchmetrics
from mlflow.data.pandas_dataset import PandasDataset

mlflow.pytorch.autolog(log_every_n_epoch=1, log_every_n_step=None, 
                        log_models=True, log_datasets=True, disable=False,
                        exclusive=False, disable_for_unsupported_versions=False,
                        silent=False, registered_model_name=None, extra_tags=None
                        )

import mlflow.pytorch
from mlflow.client import MlflowClient

model_name = "NeuralProphet"

with mlflow.start_run() as run:

    dataset: PandasDataset = mlflow.data.from_pandas(df, source="AirPassengersDataset")

    # Log the dataset to the MLflow Run. Specify the "training" context to indicate that the
    # dataset is used for model training
    mlflow.log_input(dataset, context="training")
   
    mlflow.log_param("model_type", "NeuralProphet")
    mlflow.log_param("n_lags", 8)
    mlflow.log_param("ar_layers", [8, 8, 8, 8])
    mlflow.log_param("accelerator", "gpu")

    #To Train 
    # Import the NeuralProphet class
    from neuralprophet import NeuralProphet, set_log_level

    # Disable logging messages unless there is an error
    set_log_level("ERROR")

    # Create a NeuralProphet model with default parameters
    m = NeuralProphet(n_lags=8,  
                  ar_layers=[8, 8, 8, 8],
                  trainer_config = {"accelerator":"gpu"})

    # Use static plotly in notebooks
    m.set_plotting_backend("plotly-resampler")

    # Fit the model on the dataset
    metrics = m.fit(df)

    df_future = m.make_future_dataframe(df, n_historic_predictions=48, periods=12)

    # Predict the future
    forecast = m.predict(df_future)



mlflow.metrics.mae()
mlflow.pytorch.get_default_conda_env()
mlflow.pytorch.get_default_pip_requirements()

#Registering model
model_uri = f"runs:/{run.info.run_id}/NeuralProphet_test"
mlflow.register_model(model_uri=model_uri, name=model_name)

**Comment by cargecla1** [comment]
Hello @SimonWittner,

As previously discussed, I have started and new branch and sent a pull request to add another example to use MLflow with NeuralProphet for your review.

Please refer to: https://github.com/ourownstory/neural_prophet/pull/1499

Looking forward to hear more from you.

Cheers.
