### ISSUE TITLE
Yearly seasonality shows "2017" in model.plot_parameters().show()

### ISSUE THREAD

**Issue by wasnertobias** [ourownstory/neural_prophet#1500]
![image](https://github.com/ourownstory/neural_prophet/assets/1354793/19be5768-9f52-41af-ad1f-56cacfb779d1)

Would be less confusing to show Months only and no year at all.

**Comment by SimonWittner** [comment]
Hi @wasnertobias, 
thanks for raising this! Is the period you are looking at in 2017? Could you share your code to reproduce this?

**Comment by wasnertobias** [comment]
No, neither my training data nor my forecasted timeframe has anything to do with 2017.

I expect this to happen with any plot_parameters() call. 

Will provide a code example, but this will take me a few weeks as currently busy finishing up my master thesis.

**Comment by wasnertobias** [comment]
I just checked. It even shows up in the docs: https://neuralprophet.com/tutorials/tutorial03.html#Tutorial-3:-Seasonality (3rd figure)

**Comment by SimonWittner** [comment]
Hi @wasnertobias, 
I am assuming you are using plotly as the plotting backend? As a quick fix, you could use 'matplotlib' as your plotting backend.

**Comment by SimonWittner** [comment]
Solved with #1501
