### ISSUE TITLE
An error occurred

### ISSUE THREAD

**Issue by Ambitioning** [ourownstory/neural_prophet#1503]
When I'm using these few lines of code：
future=m.make_future_dataframe(df,periods=180)
forecast=m.predict(future)
forecast.head()
This error will appear：'DataFrame' object has no attribute 'append'
What is this problem?

**Comment by SimonWittner** [comment]
Hi,
could you please verify if you are also facing this error when using a different dataframe? 
You could for example use this: 
`df = pd.read_csv("https://github.com/ourownstory/neuralprophet-data/raw/main/kaggle-energy/datasets/tutorial01.csv")`

**Comment by mete10** [comment]
Hi Simon,

I get the same error even if I use the dataframe you provided above.

Any idea on how to solve this? Is it related to the Neural Prophet installation process?
