### ISSUE TITLE
Info: Ideal Memory and CPU size

### ISSUE THREAD

**Issue by aravindravva** [ourownstory/neural_prophet#1517]
Hey there 

We are running the nueral prophet model on a production server  of 1.5GB CPU and 1 GB Memorry , seeing CPU spikes and run time issues quite often,

What will be the ideal size of CPU and Memory 

Is GPU required ?
we have the code that hits the model simulatneously from multiple services, each has 90 rows x 2 columns

**Comment by SimonWittner** [comment]
Hi,

to speed up your training you can use a GPU. However, we are currently working on a solution to make the training way more efficient.

**Comment by aravindravva** [comment]
Thanks for the response
