### ISSUE TITLE
Steps To Setup

### ISSUE THREAD

**Issue by quant-exchange** [ourownstory/neural_prophet#1522]
Hey,

I found out about this project today and wanted to give it a spin. I had a few basic issues getting it to install and run using a few different Python version virtual ENV's; 3.9 was the one that I ended up getting it to work with, but had issues on other versions.

Here's what I did to get it to work in Jupyter + Conda:

# setup
conda create -n NAME python=3.9
conda activate NAME

# install and setup kernal
pip install neuralprophet
conda install ipykernel
python -m ipykernel install --user --name 3.9env --display-name "NP Forecast Test"

This worked for me with no issues; feature request would be to show a step by step to get it running as it's still in beta makes that more difficult for users currently.

I was able to run a forecast that I wanted to test and the results are looking good; will definitely keep studying this tool and see how to tune it!

Thanks,

Q.E.

**Comment by mmangione** [comment]
We run this on Ubuntu 20.04 & 22.04 systems with Python 3.10 - and also MacOS (latest) with Python 3.10 with no issues. We always use a virtualenv. We did have issues with 3.11, but I haven't tried that since 10/23

**Comment by SimonWittner** [comment]
Hey @quant-exchange,
thanks for raising this! We will take a closer look and see what we can do!

**Comment by ourownstory** [comment]
@mmangione the newest state on main now supports up to Python 3.12 (but no longer 3.8). Feel free to try it again.

Please also let us know which setup steps exactly might be helpful!

**Comment by quant-exchange** [comment]
Our newest python docker image I believe is using 3.12; so we'll play around with that when figuring out the retrain weight save/load logic ideas; thanks!
