### ISSUE TITLE
cpu only library version ? 

### ISSUE THREAD

**Issue by mikekuzak** [ourownstory/neural_prophet#1528]
Hi there,

is there any version which is just for CPU ? Basically it gets ridiculous if CUDA  lib dependencies are over 1GB, and we don't have GPUs. 
Many packages that have both GPU and CPU versions will have different installation commands or options to specify the desired version. ```tensorflow-cpu```

Or is there any other way of managing this. I'm using Anaconda3
Thanks

**Comment by SimonWittner** [comment]
Hi, 
thanks for raising this! We are currently working on making NP more memory-efficient. 
You could check in your notebook if a GPU is available and then also use it during training with the following code: 

    # Check if GPU is available
    use_gpu = torch.cuda.is_available()

    # Set trainer configuration
    trainer_configs = {
        "accelerator": "gpu" if use_gpu else "cpu",
    }
    print(f"Using {'GPU' if use_gpu else 'CPU'}")

    # Model
    m = NeuralProphet(**trainer_configs)
    
I hope this helps!

**Comment by mikekuzak** [comment]
Hi,

Thanks for the reply. It's not about the notebook. It's about building a virtual python environment via conda or any other package dependency management software. It looks like ```neuralprophet``` has dependencies on nvidia cuda gpu libs. 

+ cudnn                        8.9.2.26  cuda11_0   

They are big, and our virtual env. are now 2GB Disk Space, because of the these dependencies we are not even using. 
Hope that makes sense. 

Maybe you could make another package called ```neuralprophet-cpu``` without there dependencies?

**Comment by ourownstory** [comment]
@mikekuzak We do not specify the torch version - as in cpu vs gpu. Torch seems to default to GPU though. You can however install the CPU only torch *before* installing neuralprophet, it will then use that version.
[`conda install pytorch cpuonly -c pytorch`](https://pytorch.org/get-started/locally/)

**Comment by ourownstory** [comment]
I tried to work out a solution for adding this as an option, but ran into some limiting issues due to the setup only working for specific platforms/versions. The simplest option is to install the desired torch version beforehand. 

Please feel free to re-open if this does not work for you
