### ISSUE TITLE
Update `utils.save` docs to support path-like / io.Bytes output

### ISSUE THREAD

**Issue by charlesverdad** [ourownstory/neural_prophet#1553]
The `neuralprophet.utils.save` function accepts a `path:str` as the second argument.
This makes me believe that I can only save to a file. However upon looking at the code, it actually
just passes the `path` to `torch.save`'s `f` parameter, which accepts io.BytesIO buffer.

Specifically, [torch.save](https://pytorch.org/docs/stable/generated/torch.save.html) supports the type: [Union](https://docs.python.org/3/library/typing.html#typing.Union)[[str](https://docs.python.org/3/library/stdtypes.html#str), [PathLike](https://docs.python.org/3/library/os.html#os.PathLike), [BinaryIO](https://docs.python.org/3/library/typing.html#typing.BinaryIO), [IO](https://docs.python.org/3/library/typing.html#typing.IO)[[bytes](https://docs.python.org/3/library/stdtypes.html#bytes)]]

This means it is already possible to use utils.save to write to memory. But the typehints and doc doesn't state that.

**Comment by SimonWittner** [comment]
Hi @charlesverdad, 
thanks for raising this! We'll change that. If you want, you could also create a PR for this.
