### ISSUE TITLE
The Version on `conda-forge` Oudated (`0.6.2`)

### ISSUE THREAD

**Issue by RoyiAvital** [ourownstory/neural_prophet#1555]
The [current version on `conda-forge` is `0.6.2`](https://anaconda.org/conda-forge/neuralprophet):

![image](https://github.com/ourownstory/neural_prophet/assets/7347975/6497ea44-940c-48ac-b256-0fca2fb0100e)

Any chance to update it to the latest version?

**Comment by rongxin1** [comment]
yup...I am also looking forward to having newer version of NueralProphet on conda-forge.

**Comment by MaiBe-ctrl** [comment]
@ourownstory To be considered for the next release: update the version of neuralprophet on conda-forge!

**Comment by ourownstory** [comment]
It appears that after an initial request to add a package to `conda-forge`, which was [done here](https://github.com/conda-forge/staged-recipes/pull/23383) by @VaTupuri, they will pull subsequent releases from PyPI, [based on this resource](https://www.pyopensci.org/python-package-guide/tutorials/publish-conda-forge.html). 
Thus, @rongxin1 and @RoyiAvital I recommend commenting on the linked conda-forge PR. 

Also, Anaconda themselves appear to have included `neuralprophet 0.8.0`, though the version history is spotty and there seems to be a substantial delay. 

Please report back here if there is something that we could do on our end to support the conda releases!

**Comment by ourownstory** [comment]
Closing this for now until it becomes clear what we can do on our end. Please feel free to reopen!

**Comment by koenklomps** [comment]
Is there a way to download an updated version of this package via conda? On the main anaconda channel the windows version is very [outdated](https://anaconda.org/main/neuralprophet). The [conda-forge version](https://anaconda.org/conda-forge/neuralprophet) is still 0.6.2.

@ourownstory
