### ISSUE TITLE
SGD optimizer provides invalid forecast with NaN

### ISSUE THREAD

**Issue by dc0709** [ourownstory/neural_prophet#1625]
I am trying to fine-tune the NeuralProphet model for time series forecasting.

When I use `optimizer="AdamW"`, everything works correctly. However, when I set `optimizer="SGD"`, the `fit()` method returns `NaN` metrics, and the corresponding `predict()` method provides `NaN` predictions. In both cases, I set `learning_rate=None`.

Example:
![image](https://github.com/user-attachments/assets/fa302ad3-9dbe-4edd-9aa0-b66c89ab76ec)

Why does this issue occur with `optimizer="SGD"` and how can it be resolved?

**Comment by ourownstory** [comment]
When setting a manual optimization method, I suggest to also set and tune appropriate learning rates, and potentially epochs and batch sizes.
