### ISSUE TITLE
Fitting time increase between 0.9.0 and 1.0.0rc10 upgrade,and old model file can not be used

### ISSUE THREAD

**Issue by frankelau** [ourownstory/neural_prophet#1631]
0.9.0 cost 39s ,upgraded to 1.0.0rc10 cost 290s. 
and old model file can not be used

**Comment by ourownstory** [comment]
@frankelau 
This may be partially connected to #1629 Pytorch Lightning 2.0 is causing some machines to experience up to 10x longer training times. We raised an issue with them. 

Beyond, there are some fundamental model and especially data pipeline changes for 1.0.0, that we are currently optimizing. Please use the 1.0.0rc versions only as preview for UI changes but not as production models yet. 

The current main version should already be a good bit faster compared to 1.0.0rc10.

**Comment by ourownstory** [comment]
Please share more on what issues you are experiencing with model reuse. There are some substantial changes of the inner workings moving to 1.0.0, thus it is helpful for us to understand how those may be affecting your use case.

**Comment by ourownstory** [comment]
@frankelau This issue should have been largely resolved now with the current main branch. Please do share your experience.
