### ISSUE TITLE
'Train' object has no attribute 'lambda_delay'

### ISSUE THREAD

**Issue by dorgol** [ourownstory/neural_prophet#174]
I was trying to predict a monthly series. It works with no AR, but when I add AR it fails and gives the following error:
"'Train' object has no attribute 'lambda_delay'". I was looking in your code and you are using 'self.config_train.lambda_delay' without defining it anywhere. What am I missing?

**Comment by ourownstory** [comment]
Hi @dorgol, This bug happened due to epochs not being defined at the time of initiating lambda_delay. 

Meanwhile, this has been been fixed and merged in PR #172. 
Pulling the latest version of master should resolve the issue. 

If the issue persists, please feel free to reopen the issue.
