### ISSUE TITLE
cross_validation utility

### ISSUE THREAD

**Issue by gkumarg** [ourownstory/neural_prophet#180]
In Prophet diagnostics, we have cross_validation and performance_metrics. Is there an equivalent in NeuralProphet?

Sample:
from fbprophet.diagnostics import cross_validation, performance_metrics

I am still a noob, so my apologies if this question does not belong here.

**Comment by ourownstory** [comment]
Hi @gkumarg,
We currently do not have a cross_validation function. However, we do have validation functions:
https://ourownstory.github.io/neural_prophet/#validation

You could first do a split into folds and then use those functions to do CV. 
We will eventually add a helper function for this.

In terms of metrics: a few are collected and returned by the fit and test functions.

Support for customization of metrics is planned to be added soon.

**Comment by gkumarg** [comment]
Thank you! I will try that approach.

**Comment by ourownstory** [comment]
@gkumarg now there is a basic utility, see  #226

**Comment by gkumarg** [comment]
Thanks @ourownstory !
