### ISSUE TITLE
Docstring: add example how to use future regressors

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#181]
potentially also a short tutorial notebook.

**Comment by mekriti** [comment]
Hi Team,
Thanks for creating this.

**Comment by ourownstory** [comment]
Looking forward to your pull request @mekriti!
Here are a few resources for you:
* Contributing to a project by forking, then adding a pull request: https://github.com/ourownstory/swiss-cheese/blob/master/git_best_practices.md
* fbprophet add_regressor example: https://facebook.github.io/prophet/docs/seasonality,_holiday_effects,_and_regressors.html#additional-regressors
* while the fbprophet example is alright, a better example would be something like an energy prediciton regressed on temperature forecast. Either way, narrating/explaining the process in the example notebook with some Markdown cells would be great (similar to the other notebooks).

**Comment by karl-richter** [comment]
Addressed by https://neuralprophet.com/tutorials/future-regressors.html.
