### ISSUE TITLE
splitting into train and validation set when n_lag > 0

### ISSUE THREAD

**Issue by gkumarg** [ourownstory/neural_prophet#186]
I was trying to split a sub-daily dataset (hourly) with 43824 rows using m.split_df(df, valid_pct=0.2) and noticed that it is returning 1461 rows for training and 366 for validation set. If I set the n_lag value in setting up the model as 0, I get 35060 and 8764 as expected. If I use any other number, the split is returning based on "daily" frequency by the looks of it.
nprophet.df_utils - split_df may need an update.

**Comment by ourownstory** [comment]
Thank you @gkumarg, we will look into this!

**Comment by ourownstory** [comment]
@gkumarg is the issue now resolved for you?

**Comment by gkumarg** [comment]
@ourownstory Sorry Oskar. It does not seem to be working. I tried it on the yosemite dataset and noticed the same issue with split_df. It works fine for n_lag = 0.

`m = NeuralProphet(
    n_changepoints=0,
    weekly_seasonality=False,
    n_lags=1
)

df_train, df_val = m.split_df(df, freq= '5min', valid_p=0.2)
print("train set size:", df_train.shape)
print("Validation set size:", df_val.shape)`

**Comment by ourownstory** [comment]
@gkumarg 
I am sorry to hear that. 
Have you tried installing the latest version directly from this github?

Thank you for providing a code example. I will try to reproduce it.

**Comment by ourownstory** [comment]
@gkumarg 
Found and fixed the actual issue (it was in the logic to fill in missing data).

Please give it another shot now!

**Comment by gkumarg** [comment]
Checked with the latest version and looks good! Thanks!
