### ISSUE TITLE
What is yhat1

### ISSUE THREAD

**Issue by DaToKi** [ourownstory/neural_prophet#201]
![2020-12-09_101346](https://user-images.githubusercontent.com/45854141/101609451-44e56b00-3a07-11eb-9544-8deb055582b7.jpg)
In the created df forecast there is ds and y.

What are the values of yhat1?

**Comment by HansikaPH** [comment]
Hi @DaToKi, yhat1 values are the predictions from the model. In this case, since you are forecasting into the future, the true y values are not available, but the forecasts(yhat1) are available from the model.

**Comment by ourownstory** [comment]
@DaToKi if you do not specify any `n_lags`,  `yhat1` is identical to the returned `yhat` in fbprophet. 

if `n_lags > 0` is specified, the number 'n' after `yhat'n'` refers to the 'n'-th step forecasted into the future, up to `n_forecasts` steps.
