### ISSUE TITLE
series data - non time stamped

### ISSUE THREAD

**Issue by andrewcztrack** [ourownstory/neural_prophet#218]
hi @ourownstory !!!

love the library! it super cool!

Just wondering if there are plans to implement non time series data. e.g if you have a single nx1 numpy array, create forecasts 30 steps ahead.

Kind regards and thanks,
Andrew

**Comment by ourownstory** [comment]
Hi Andrew @andrewcztrack,
Thank you!
Do you mind explaining your specific problem setting a little closer?

From what I understand, you are talking about tabular data, where the predicted vector is a forecast. 
For this application, sklearn and fastai have excellent support.
