### ISSUE TITLE
Multiple Inputs in Neural Prophet

### ISSUE THREAD

**Issue by karthikraja95** [ourownstory/neural_prophet#220]
How can I use multiple inputs in Neural Prophet? By looking at the example notebooks I see we need to have two columns ds as date and y as a target variable?

My question is how to add other features with ds (Date). For example, some categorical features to be considered by the neural prophet model?

**Comment by HansikaPH** [comment]
For categorical features, please see the discussion #139

**Comment by ourownstory** [comment]
> By looking at the example notebooks I see we need to have two columns ds as date and y as a target variable?

Yes, that is the minimal input.

> My question is how to add other features with ds (Date). 

May [events](https://github.com/ourownstory/neural_prophet/blob/master/example_notebooks/events_holidays_peyton_manning.ipynb) or a type of [regressor](https://ourownstory.github.io/neural_prophet/model/future-regressors/) serve your needs?

**Comment by ourownstory** [comment]
@karthikraja95 

> By looking at the example notebooks I see we need to have two columns ds as date and y as a target variable?

Yes, that is the minimal input.

> My question is how to add other features with ds (Date). 

May [events](https://github.com/ourownstory/neural_prophet/blob/master/example_notebooks/events_holidays_peyton_manning.ipynb) or a type of [regressor](https://ourownstory.github.io/neural_prophet/model/future-regressors/) serve your needs?
