### ISSUE TITLE
Multivariate time series

### ISSUE THREAD

**Issue by loretoparisi** [ourownstory/neural_prophet#235]
Is it possible to forecast multivariate time series?

For instance,
 [Sagemaker DeepAR](https://docs.aws.amazon.com/sagemaker/latest/dg/deepar.html) has as _target_ an array of floating-point values or integers that represent the time series to forecast.

Thanks

**Comment by HansikaPH** [comment]
@loretoparisi Thanks for this comment. Multivariate forecasting is something quite important and we do hope to support it at some point. But, currently, we do not have it implemented. If you would like to have a start on this on the codebase, we would be happy to help and collaborate.

**Comment by ourownstory** [comment]
Closing as this is partially addressed in #250 and is on the future features agenda.
