### ISSUE TITLE
colab install fails?

### ISSUE THREAD

**Issue by microprediction** [ourownstory/neural_prophet#241]
Has anyone else noticed that neuralprophet doesn't install from colab, even after !pip install --upgrade pip

Workaround:

    !pip install git+https://github.com/ourownstory/neural_prophet.git

Is there something about colab I'm missing?

**Comment by microprediction** [comment]
I see the same workaround here

    https://github.com/ourownstory/neural_prophet/blob/master/example_notebooks/season_multiplicative_air_travel.ipynb

Since this is a colab issue safe to close I guess.

**Comment by ourownstory** [comment]
Hi @microprediction 
In order to support colab, we had to back-port NP to python 3.6, which our release candidate 2.8 has done. 
Once it is released to pip, you won't have to do the workaround anymore.
