### ISSUE TITLE
NeuralProphet  Document in Chinese

### ISSUE THREAD

**Issue by SharkFin-top** [ourownstory/neural_prophet#244]
Thank you for your contribution! I really like NeuralProphet and would like to get more people to use it. So I have translated the document into Chinese. 

GitHub: https://github.com/SharkFin-top/neuralprophet-doc-zh

Thank you！

**Comment by ourownstory** [comment]
Thank you @SharkFin-top!

Do you mind making a pull request, adding the md pages under `docs/zh/`?
I will then integrate them with our documentation, hosted under [neuralprophet.com](https://neuralprophet.com)


Really appreciate your contribution, this will greatly serve our Chinese users!
