### ISSUE TITLE
Multivariate Features: create wrapper

### ISSUE THREAD

**Issue by abhi0444** [ourownstory/neural_prophet#250]
Can this model used with multiple features with dates to.

**Comment by HansikaPH** [comment]
@abhi0444 If the multiple features that you need to add are just external variables, you can do this by adding them as either future regressors or lagged regressors, depending on whether you have the future values for these features available too. Please refer to Sections [Lagged Regressors](http://neuralprophet.com/model/lagged-regressors/) and [Future Regressors](http://neuralprophet.com/model/future-regressors/) of the documentation to find more details on how to do this.

If the features that you want to add, also need to be forecasted for the future (as in a multivariate forecasting setting), we currently do not have support for that. We do hope to have this at some point in a later release.

**Comment by glopezzz** [comment]
If you're asking about training NeuralProphet models with different variables/features, you can train one model per feature with a loop. This is the function I use:


def train_fbprophet_model(X_train,train_dates):
    
    X_train = X_train[:,1:-1]
    X_sep = []

    for var in range(X_train.shape[1]):

        data = {"ds":train_dates, "y":X_train[:,var]}
            
        X_sep.append(pd.DataFrame(data))
        
    models = {}

    for var in range(X_train.shape[1]):
        models[var] = NeuralProphet()
        models[var].fit(X_sep[var])
    
    return models

**Comment by ourownstory** [comment]
@glopezzz if you would like to make this into a proper helper function, I would be happy to approve your pull request.

**Comment by yasirroni** [comment]
> one model per feature 

Sadly, one model per feature will ignore correlation between time-series.

**Comment by yasirroni** [comment]
Maybe, look at https://github.com/vonum/multi-prophet? I don't know what he is doing thought to extend prophet to process multivariate.

**Comment by ourownstory** [comment]
@yasirroni if you specify the other series as lagged inputs, you will get a regression on them  not classical VAR, but close enough. 
If you wanted to go all the way, you could train a final model that takes all predicted series as future regressors, regressing them onto your target series. 
Not elegant, but would work.

If anyone would like to take on a project to support multi-series forecasting, I would be happy to support them!

**Comment by yasirroni** [comment]
> you could train a final model that takes all predicted series as future regressors, regressing them onto your target series.
Isn't the same as one model per feature, but adding an extra final model on top of the many model for each feature?

> If anyone would like to take on a project to properly support multi-series forecasting, I would be happy to help them!

I want, but I did not have the competency. I'm not good both at statistic and machine learning.
__
Can't we simply change the training process to be 2 dimensional time series with fully connected node to process relation between time series? #CMIIW

**Comment by ourownstory** [comment]
> Isn't the same as one model per feature, but adding an extra final model on top of the many model for each feature?
I am not sure if I understand your question correctly, but yes, the final model is not necessary.




> Can't we simply change the training process to be 2 dimensional time series with fully connected node to process relation between time series?
Yeah kind of. Ideally we would allow the user to have a more classic VAR setup or a NN setup.
The main work is more to make the API, preprocessing and postprocessing changes to the library in a way that does not interfere with current functionality and usability. 

If you are fit with Python, and are willing to put in the work, I can take care of the stats/ML parts, as those are mostly isolated to the model formulation itself.
