### ISSUE TITLE
add model.get_params and set_params 

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#252]
similar to scikit model.get_params

for scenario testing or for parameter-based save / load functions

**Comment by anastasiia-tovstolis** [comment]
Hello @ourownstory, Can you assign this issue to me?

**Comment by karl-richter** [comment]
Hi @ourownstory, @anastasiia-tovstolis, with our ongoing migration to Pytorch Lightning (and I think also in plain pytorch) you can access the model parameters using `m.model.state_dict()`. This yields the trained parameters such as bias, trend etc. Further you can use `load_state_dict()` to set the parameters of the model. Not sure if this is exactly what you are looking for, but it seems very related.

**Comment by anastasiia-tovstolis** [comment]
Hi @ourownstory, I would like to clarify if this issue is still relevant in connection with the comment @karl-richter?

**Comment by noxan** [comment]
Also that we do not forget @Kevin-Chen0's contributions on the other issue

> Add `m.summary()` (from [Keras](https://keras.io/api/models/model/#summary-method)), `m.state_dict()` (from [PyTorch](https://pytorch.org/tutorials/recipes/recipes/what_is_state_dict.html)), and/or `m.parameters()` (also from PyTorch) methods into the NeuralProphet module.
> 
> This makes it easier to show and port the NeuralProphet parameters, including for seasonality, lags, changepoints, and others.

> Create `m.state_dict()` for display the NeuralProphet hyperparameters in the dictionary format. Can also be called `n.hyperparameters()`.

**Comment by anastasiia-tovstolis** [comment]
Yesterday I finished these steps, I hope it's well done)
@noxan @ourownstory

**Comment by noxan** [comment]
Closing thanks to the pull request of @anastasiia-tovstolis
