### ISSUE TITLE
how to set changepoint manually

### ISSUE THREAD

**Issue by ramdhan1989** [ourownstory/neural_prophet#259]
is there any example of setting manual changepoint ? I got this on doc 

> changepoints (np.array): List of dates at which to include potential changepoints. If
        not specified, potential changepoints are selected automatically.

I tried but end up with following error :
`\neuralprophet\time_net.py in __init__(self, config_trend, config_season, config_covar, config_regressors, config_events, config_holidays, n_forecasts, n_lags, num_hidden_layers, d_hidden)
     83             self.segmentwise_trend = self.config_trend.trend_reg == 0
     84             self.trend_k0 = new_param(dims=[1])
---> 85             if self.config_trend.n_changepoints > 0:
     86                 if self.config_trend.changepoints is None:
     87                     # create equidistant changepoint times, including zero.

TypeError: '>' not supported between instances of 'list' and 'int'
`

thanks

**Comment by ourownstory** [comment]
hi @ramdhan1989 
Does converting the list to an nd.array solve the issue?
