### ISSUE TITLE
feature: model saving and loading functions using torch

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#27]
inspiration 
https://github.com/cs230-stanford/cs230-code-examples/tree/master/pytorch

Can simply save/load NeuralProphet.model
https://pytorch.org/tutorials/beginner/saving_loading_models.html

Issue:
must also store hyperparameter settings and any settings for events, regressors, etc.
may need a change in how configurations are stored/initialized

How: 
We should implement this using torch.save() and torch.load()
with the recommended way of storing pytorch models 
https://stackoverflow.com/questions/42703500/best-way-to-save-a-trained-model-in-pytorch

**Comment by themindfactory** [comment]
hmm... looking to save models.... no luck on the webs....

**Comment by mandar-avhad** [comment]
Hi, any latest update on how to save, load the neural prophet model and then predict using the saved model?
Please share the steps/code!

**Comment by ourownstory** [comment]
merged in #691

**Comment by ourownstory** [comment]
@jaismith would you like to implement a model-parameter based saving function?
A first step would be to address: #252
