### ISSUE TITLE
inferred freq warning

### ISSUE THREAD

**Issue by karim-soufi** [ourownstory/neural_prophet#272]
Can we have a warning when training the model if the ds columns doesn't have a set freq. 
This is particularly useful when using the make_future_dataframe, as it will default to the days when freq is None.

**Comment by ourownstory** [comment]
Hi @karim-soufi, the current behavior is to require the user to set the `freq` at `model.fit(...)`.
This will be saved in the model and used in `make_future_dataframe`.
The reason is to ensure identical meaning of lagged inputs and multiple step ahead forecasts.

Do you mind explaining in more detail what you are trying to achieve?

**Comment by karim-soufi** [comment]
Hello @ourownstory , I happened to train a model where the series didnt have an inferred frequency (it was monthly). when doing the make_future_dataframe, the model to predict future dataframe on a daily basis. 

It would be helpful, that during training if the freq is unset, the model would throw a warning. Most forecasting models do that, if I am not mistaken.

Just to catch the attention of the user.

**Comment by ourownstory** [comment]
> It would be helpful, that during training if the freq is unset, the model would throw a warning.

I agree. I thought it did actually throw an error, as the positional `freq` arg does not have a default value. 
You might have unveiled some unintended behavior. Do you mind sharing a minimal piece of code for me to reproduce the issue?

**Comment by karim-soufi** [comment]
I believe setting the  arg `freq` to `None` would be sufficant to recreate it in the case where I woud be using `df.ds.inferred_freq` to set it while pandas didnt manage to infer a frequency for some reason (e.g. a gap in the series).
