### ISSUE TITLE
Possibility to disable FileHandler writing out logs 

### ISSUE THREAD

**Issue by stiebels** [ourownstory/neural_prophet#290]
Hello,

NeuralProphet forces writing out of logging to log.logs. However, in environments where the package does not have permission to write files, this causes errors.

Is there a way to control or deactivate the logging behaviour of the package?

`Traceback (most recent call last):
  File "./script.py", line 3, in <module>
    from x.y import Y
  File "/usr/local/lib/python3.8/site-packages/x/y.py", line 7, in <module>
    from x.model import (
  File "/usr/local/lib/python3.8/site-packages/x/y.py", line 6, in <module>
    from neuralprophet import NeuralProphet
  File "/usr/local/lib/python3.8/site-packages/neuralprophet/__init__.py", line 7, in <module>
    f_handler = logging.FileHandler("logs.log", "w+")
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/local/lib/python3.8/logging/__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/service/logs.log'`

Happy to make a corresponding PR if this indeed is unwanted behaviour.

**Comment by polly-morphism** [comment]
I have the same issue, trying to use this inside docker and I get 

celery_worker    |   File "/usr/src/app/predictions/utils.py", line 3, in <module>
celery_worker    |     from neuralprophet import NeuralProphet
celery_worker    |   File "/usr/local/lib/python3.7/site-packages/neuralprophet/__init__.py", line 7, in <module>
celery_worker    |     f_handler = logging.FileHandler("logs.log", "w+")
celery_worker    |   File "/usr/local/lib/python3.7/logging/__init__.py", line 1087, in __init__
celery_worker    |     StreamHandler.__init__(self, self._open())
celery_worker    |   File "/usr/local/lib/python3.7/logging/__init__.py", line 1116, in _open
celery_worker    |     return open(self.baseFilename, self.mode, encoding=self.encoding)
celery_worker    | PermissionError: [Errno 13] Permission denied: '/usr/src/app/logs.log'

**Comment by stiebels** [comment]
Fyi, my workaround so far is to create the file that neuralprophet outputs its logs to at container build time and provide it with write privileges. So essentially in my Dockerfile:

`RUN touch /usr/service/logs.log && chmod 777 /usr/service/logs.log`

**Comment by microprediction** [comment]
Second the request to suppress this writing of log files.
