### ISSUE TITLE
More than 30 consecutive missing values encountered in column y

### ISSUE THREAD

**Issue by Asanoci** [ourownstory/neural_prophet#292]
Hello,
First of all, thank you for the great job you did on this library.
I am new to it, I worked with _facebook's prophet_, and wanted to try _neuralprophet_ now.

I ran into this error: 
`More than 30 consecutive missing values encountered in column y. Please preprocess data manually.`

I understand what is means, but, in my case, I only have data for 10:00 to 20:00 everyday for a year, in consequence I would like to forecast only for these hours.

Is there a workaround ?

Thank you !

**Comment by Asanoci** [comment]
hello,
I have found a workaround here:

https://github.com/ourownstory/neural_prophet/discussions/262

Thank you!

**Comment by ourownstory** [comment]
Hope it worked as expected?
If not, you could try to strecht the 10h/day to 24h/day. This would allow you to use auto-regression, too.
