### ISSUE TITLE
suppress creation of logs.log?

### ISSUE THREAD

**Issue by microprediction** [ourownstory/neural_prophet#311]
Request: Option to suppress creation of logs.log as this seems like an unfortunate side effect in some settings.

**Comment by dgonier** [comment]
Specifically, lambda doesn't allow it for AWS... So it makes it impossible to even load the module

**Comment by ourownstory** [comment]
I am sorry to hear that. We will suppress it by default then.

**Comment by ourownstory** [comment]
@microprediction and @dgonier 
Plese let me know if #348 resolved the issue.
