### ISSUE TITLE
Benchmarking and neural prophet residual prediction

### ISSUE THREAD

**Issue by microprediction** [ourownstory/neural_prophet#316]
Hi. 

I noticed that modeling model bias might be on the short-term roadmap. To the extent that it helps, I am running bake-offs that include some neural prophet residual prediction. I picked a few different orders (see [code](https://github.com/microprediction/timemachines/blob/main/timemachines/skaters/nproph/nprophetskaters.py)) and those appear in the [Elo ratings for time series models](https://microprediction.github.io/timeseries-elo-ratings/html_leaderboards/univariate-k_003.html). 

Amongst them is nprophet_p1_hypocratic and it's ilk (defined [here](https://github.com/microprediction/timemachines/blob/main/timemachines/skaters/nproph/nprophskaterscomposed.py) ) which is an attempt to stack a residual prediction after neural prophet. To be honest this stuff is messing with my head and in need of more context (as per my [cross val question](https://stats.stackexchange.com/questions/514694/time-series-modeling-w-shrinkage-for-time-series-model-residuals)). 

Peter

**Comment by noxan** [comment]
@LeonieFreisinger might be worth having a look at this during your benchmarking efforts

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
