### ISSUE TITLE
Questions regarding neural_prophet usages.

### ISSUE THREAD

**Issue by bergen288** [ourownstory/neural_prophet#317]
neural_prophet only gives me the plot with forecast value.  Is it possible to make make plot with history and forecast values?
The following add_seasonality works fine in fbprophet, but it fails with neural_prophet due to "unexpected keyword argument 'condition_name'".  What's the correct way to define it?
```
model.add_seasonality(name='daily_weekday',
                      period=1,
                      fourier_order=3,
                      condition_name='weekday')
```

**Comment by ourownstory** [comment]
Hi @bergen288 

> neural_prophet only gives me the plot with forecast value. Is it possible to make make plot with history and forecast values?

Yes, you can use ```plot_last_forecast(plot_history_data=True)```

> The following add_seasonality works fine in fbprophet, but it fails with neural_prophet due to "unexpected keyword argument 'condition_name'". What's the correct way to define it?

I am sorry to say that conditional seasonality is not implemented yet.
