### ISSUE TITLE
add_lagged_regressor produces None forecasts

### ISSUE THREAD

**Issue by geoffstowe** [ourownstory/neural_prophet#319]
Running the test_lag_reg function from test_integration.py and looking at the forecast, it seems to have None for 6 out of the 7 yhat forecasted values.  It also looks like the lagged_regressor columns don't get populated correctly, which may be the cause:

![image](https://user-images.githubusercontent.com/33644741/116505383-9cc62680-a86f-11eb-8c9c-a61813d752ea.png)

**Comment by ourownstory** [comment]
![image](https://user-images.githubusercontent.com/21246060/123539505-c7830d00-d742-11eb-95ce-915c8ccb3781.png)
