### ISSUE TITLE
'missing dates were added' issue

### ISSUE THREAD

**Issue by skybullet1987** [ourownstory/neural_prophet#336]
Hi,

I am new to NeuralProphet.

I have been trying to use it and I have the following issue:

My data originally had missing dates and values.

I fixed it with pad dates, now:
```
df['ds'].isna().sum() is 0
df.isnull().sum() is 0
```

However, when I start fitting the model, I get:

`INFO: nprophet - _handle_missing_data: 190 missing dates were added.`

And when I want to use it:

`'More than 30 consecutive missing values encountered in column y. Please preprocess data manually.'`

I am not sure what should I do and what these missing values are, because I can't identify them.

**Comment by ourownstory** [comment]
Hi @skybullet1987 

Welcome to NeuralProphet!

You correctly seem to have filled dates with NAs

What this test is checking for is not just NAs, but also missing data samples.

e.g. if you have daily data for March June, July, but not for April and March, it will throw this error.

another source could be if you set the incorrect data `freq`.

Please share whether this info helped you resolve this. 

Thank you, 
Oskar
