### ISSUE TITLE
Add documentation for highlight_nth_step_ahead_of_each_forecast

### ISSUE THREAD

**Issue by limoon20** [ourownstory/neural_prophet#337]
Would you please tell me if you've seen this issue:

neuralprophet/forecaster.py",
line 1059,
in highlight_nth_step_ahead_of_each_forecast
    assert step_number <= self.n_forecasts
AssertionError

I get this error when using (analyzing S&P500 dataset):
plot_forecast(model, sp500_data, periods=60, historic_pred=False, highlight_steps_ahead=60)
Before this, it runs fine.

Thank you for your time,
LM

**Comment by ourownstory** [comment]
Hi @limoon20 
`highlight_nth_step_ahead_of_each_forecast` tells the model that you are interested in the forecast 60 steps ahead of known data.
it can be at most as large as `n_forecasts`

**Comment by karl-richter** [comment]
Closed due to inactivity. The function `highlight_nth_step_ahead_of_each_forecast` is documented by #582.
