### ISSUE TITLE
Automate sphinx notebook intregrations

### ISSUE THREAD

**Issue by bhausleitner** [ourownstory/neural_prophet#459]
**Prerequisites**

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your issue might need further discussing before being defined as a feature request:
      Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Is your feature request related to a problem? Please describe.**

Currently, the documentation has to be manually updated, whenever contributors edit existing or add new tutorial notebooks.

**Describe the solution you'd like**

Whereas the dynamic creation of the `.nblink` files have been already automated, the `index.rst` file still misses on this automation.

**Describe alternatives you've considered**

Manual updating is not scalable.

**Additional context**

Use sphinx built in `input` functionality wihtin `.rst` files to add a complete new `.rst` file that lists all the different files.

**Comment by karl-richter** [comment]
Addressed by the documentation refactoring by @noxan.
