### ISSUE TITLE
make_future_dataframe does not add new rows

### ISSUE THREAD

**Issue by denyslazarenko** [ourownstory/neural_prophet#552]
`future = model.make_future_dataframe(df, periods=1)` does not extend a dataframe, meaning that `future == df`.

**Comment by JonasMok** [comment]
same here. I've experienced a similar problem here when I was running NP on jupyter-notebook on sagemaker. 

So, instead to use the last version (0.3.0), I decided to test downgrade the current version to 0.2.8. This solution worked to me. Besides, I've tested run it on colab and apparently it was fine too.

**Comment by ourownstory** [comment]
this should have been fixed in #562
Does it now work for you @JonasMok ?

**Comment by ourownstory** [comment]
FYI,  the last version (0.3.1) contains this fix!
