### ISSUE TITLE
Add NeuralProphet to the KATS metalearner

### ISSUE THREAD

**Issue by nlaptev** [ourownstory/neural_prophet#554]
Metalearner allows for auto picking of relevant forecasting models. 

While NeuralProphet (https://github.com/ourownstory/neural_prophet) is part of KATS, it is currently not included as part of the metalearner. 

The problem for this task is to incorporate NeuralProphet as part of KATS metalearner (https://github.com/facebookresearch/Kats/tree/main/kats/models/metalearner)

**Comment by ourownstory** [comment]
There now is an active pull request on Kats:
https://github.com/facebookresearch/Kats/pull/248

**Comment by ourownstory** [comment]
has been merged into Kats
