### ISSUE TITLE
Data is not available - 400: Invalid request

### ISSUE THREAD

**Issue by rahul4tripathi2** [ourownstory/neural_prophet#571]
Hi Team,

Can you please let me know the way to fetch neural_prophet data. 

Getting Invalid request for below url
https://raw.githubusercontent.com/ourownstory/neuralprophet-data/main/datasets/

400: Invalid request

Regards
Rahul

**Comment by rahul4tripathi2** [comment]
is this correct dataset location - https://github.com/ourownstory/neuralprophet-data

**Comment by ourownstory** [comment]
Hi @rahul4tripathi2 

Yes, you are using the right location.

To get the data using the raw content link - you have to link to a specific file:
e.g. 
https://raw.githubusercontent.com/ourownstory/neuralprophet-data/main/datasets/retail_sales.csv
