### ISSUE TITLE
ValueError: Column ds has duplicate values. Please remove duplicates. 

### ISSUE THREAD

**Issue by rahul4tripathi2** [ourownstory/neural_prophet#578]
Why this validation is required during split_df. but same data is used by multiple time series model
 df_train, df_test = m.split_df(df_im, valid_p = 0.10)

Is there any way to fix that issue?

Resource
https://aws.amazon.com/blogs/machine-learning/training-debugging-and-running-time-series-forecasting-models-with-the-gluonts-toolkit-on-amazon-sagemaker/

**Comment by ourownstory** [comment]
Hi, if your time series has duplicate dates, the model does not know which one is correct. How to handle this depends on your data (e.g. take average, use the first one, max, min, or some other processint). Thus we do not handle duplicates implicitly but ask you to pre-process them yourself. 
hope this helps.
