### ISSUE TITLE
Can you define a maximum forecast value?

### ISSUE THREAD

**Issue by flyandlure** [ourownstory/neural_prophet#587]
I'm forecasting some data that are always presented on a scale from 0 to 100. However, the baseline model I'm using sometimes forecasts values that exceed 100. 

```
model = NeuralProphet()
metrics = model.fit(data, freq="W")
```

Is there a technique I can apply to limit the upper forecast value returned, please?

Many thanks.

**Comment by ourownstory** [comment]
Hi, you can achieve this by post-processing the forecast:

`df['yhat1'] = np.maximum(0, np.minimum(100, df['yhat1'].values))`

see #537
