### ISSUE TITLE
Logging references prophet when auto disabling seasonality

### ISSUE THREAD

**Issue by italoraony** [ourownstory/neural_prophet#59]
Update logging to mention NeuralProphet. 

Current behaviour logs "Disabling daily seasonality. Run prophet with daily_seasonality=True to override this."

https://github.com/ourownstory/neural_prophet/blob/af943a2cefe583bdd39e565df9199d2fbaec62e5/neuralprophet/utils.py#L153

**Comment by ourownstory** [comment]
resolved in branch bugfixes-italo
