### ISSUE TITLE
It has sending error in df_utils.py on _normalization func()

### ISSUE THREAD

**Issue by jepetolee** [ourownstory/neural_prophet#594]
When I tried to fitting NeuralProphet(), It makes error issue: GH#31457 on pandas op()
and I checked in func _normalization () after cycled Epoch

df_utils.py
line 249: df[new_name] = df[name].sub(data_params[name].shift).div(data_params[name].scale) 

it subtracts DataFrame['ds'] and DataFrame['y'], 
so I think it needs to fix forecaster.py's data_params some where

**Environement (please complete the following information):**

 - Python environment 3.8
 - NeuralProphet version 0.3.1, install method [BOTH installed from PYPI and git ]

**Additional context**

**Comment by ourownstory** [comment]
Hi @jepetolee Does this still happen on the current version?
If so, can you please provide the minimal needed code to re-produce the issue. Thank you.

**Comment by jepetolee** [comment]
nope. i'm using this with downgraded version(0.3.0) now so, i don't know how does it work on 0.3.1.

**Comment by jepetolee** [comment]
I  updated with version(0.3.2) and check it again it still has matter.
this is minimal code
```
            prophet = NeuralProphet(seasonality_mode='multiplicative', n_forecasts=14, epochs=300, n_changepoints=200)
            data = DataFrame({'ds': data.index, 'y': data['4'].copy()})

            prophet.fit(data, validation_df=data, freq="D")
            future = prophet.make_future_dataframe(data, periods=14)
            df = prophet._prepare_dataframe_to_predict(future)
```
and here is error
```
  File "D:/CRYPTONALYTICS/Prophet/one_day_prophet.py", line 177, in <module>
    FutureProphetOneDay()
  File "D:/CRYPTONALYTICS/Prophet/one_day_prophet.py", line 101, in FutureProphetOneDay
    df = prophet._prepare_dataframe_to_predict(future)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\neuralprophet\forecaster.py", line 2106, in _prepare_dataframe_to_predict
    _ = df_utils.infer_frequency(df, n_lags=self.n_lags, freq=self.data_freq)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\neuralprophet\df_utils.py", line 1066, in infer_frequency
    df_dict, received_unnamed_df = prep_copy_df_dict(df)
  File "C:\Users\Administrator\anaconda3\lib\site-packages\neuralprophet\df_utils.py", line 43, in prep_copy_df_dict
    raise ValueError("Please insert valid df type (i.e. pd.DataFrame, dict)")
ValueError: Please insert valid df type (i.e. pd.DataFrame, dict)
```

fortunately ,it does not have error in downgraded version,  only 0.3.1 to 0.3.2 version has an error

**Comment by ourownstory** [comment]
Hi @jepetolee 
Thank you for checking and providing the minimal code.

Please not that methods starting with an `_` are not meant to be called directly, but to be used internally by the framework.
I suggest not to use them unless you are sure what you are doing. 

In your case, you can directly call on `.predict(...)` https://github.com/ourownstory/neural_prophet/blob/7d0135a0c9b02b1a0c18b66cb2310391600de2fb/neuralprophet/forecaster.py#L602
(It will call on `_prepare_dataframe_to_predict` internally)

**Comment by jepetolee** [comment]
thanksx it works
