### ISSUE TITLE
m.plot_components plots seasonality for all available history

### ISSUE THREAD

**Issue by italoraony** [ourownstory/neural_prophet#60]
m.plot_components plots the seasonality for all of the available history.

This can make some plots - like the weekly seasonality - not so easy to understand. See attachment.

According to documentation, `crop_last_n`, which would help alleviate this issue, should be ignored for seasonality.

![image](https://user-images.githubusercontent.com/1106061/92318043-cddda800-efbb-11ea-8a0f-1a475e3ce482.png)

**Comment by ourownstory** [comment]
Thank you Italo, This is an intended issue, as 'plot_components' strictly plots the components of the forecast, while 'plot_parameters' plots the parameters, including the shapes of the seasonalities for one period only.
The Issue has been reduced by by default not including the whole history, which should make it clearer to the user, what is happening, if they specifically ask it to include more history.
Might that make sense with the new plotting mechanisms?
