### ISSUE TITLE
crop_last_n  parameter of plot_components not working with residuals plot

### ISSUE THREAD

**Issue by italoraony** [ourownstory/neural_prophet#61]
Title is descriptive.

When using the parameter `crop_last_n` from `plot_components`, the *Residuals* plot is empty and not aligned with other plots.

![image](https://user-images.githubusercontent.com/1106061/92318118-7d1a7f00-efbc-11ea-8f74-a9eea0d2a458.png)

**Comment by ourownstory** [comment]
Thank you Italo, this was an issue when there were no residuals (due to being a forecast into the future).
It has been fixed now by disabling the residuals plot if there are none.
