### ISSUE TITLE
[docs] Tutorial on how to migrate from fbprophet

### ISSUE THREAD

**Issue by lleiou** [ourownstory/neural_prophet#611]
Hi, thanks for this great Python library! I have a python project that trains model and makes predictions using fbprophet. I'm currently trying to migrate to NeuralProphet but noticed that there are some differences between the two libraries, e.g. they don't share the same set of hyperparameters, some hyperparmeters have slightly different names and the training `df` for NeuralProphet cannot contain any columns that is not used by the model, etc.

**Describe the solution you'd like**

I was wondering if there is a doc that listed out common differences between the two libraries? If not, can we create a doc to list them out? I think the doc would be helpful to those who are familiar with Prophet but new to NeuralProphet and will potentially encourage more people to try out and migrate their project to using this library, thank you!

**Comment by ourownstory** [comment]
Hi @lleiou 
Great suggestion!
Maybe we can expand this documentation page with more practical migration advice: https://neuralprophet.com/html/changes-from-prophet.html
src: https://github.com/ourownstory/neural_prophet/blob/main/docs/source/changes-from-prophet.md

Or even better, you could make a tutorial notebook on how to migrate from prophet to Neuralprophet with practical examples of how to do all the things which are different. 

Would you like to create a minimal migration tutorial, so others can learn from your experience? @lleiou ?

**Comment by lleiou** [comment]
Thanks @ourownstory for your reply!

Sounds good, I can create a simple Jupyter Notebook with modeling codes using some public data to describe the difference between the two libraries. Please note that my use case was relatively simple so I won't be able to cover all the differences between the two libraries, but feel free to add more contents to the notebook once I have shared it!

**Comment by ourownstory** [comment]
@lleiou  Sounds good, looking forward to it!

**Comment by Kevin-Chen0** [comment]
Hi @lleiou, just wanted to follow up on this as I'm also interested in this migration. Did you create a PR for your work already? Thanks!

**Comment by karl-richter** [comment]
This issue has been resolved by #831.

**Comment by karl-richter** [comment]
This issue has been resolved by #831.
