### ISSUE TITLE
An incorrect name of the file neuralprophet_dev_setup in the scripts folder and in setup.py

### ISSUE THREAD

**Issue by skupr-anaconda** [ourownstory/neural_prophet#613]
**Describe the bug**
An incorrect name of the file `neuralprophet_dev_setup` (without extension `.py`) in the `scripts` folder and in `setup.py`

I'm using `conda-build` for building `neuralprohet 0.3.2` but `{{ PYTHON }} -m pip install . -vv`  fails with `[Errno 2] No such file or directory: 'scripts/neuralprophet_dev_setup'` on all platforms

**To Reproduce**

**Expected behavior**

If you rename `neuralprophet_dev_setup` to `neuralprophet_dev_setup.py` and fix this name in `setup.py`  https://github.com/ourownstory/neural_prophet/blob/6ceef5de3586375d13134152bbe4005282ef8f26/setup.py#L33 the package builds without errors

**What actually happens**

**Screenshots**

**Environement (please complete the following information):**

 - Python environment: python 3.7-3.10
 - Platforms: osx-64, osx-arm64, linux-64, linux-ppc64le, linux-s390x, win64
 - NeuralProphet version 0.3.2 and install method `conda-build .`

**Additional context**

1. My patch to fix the issue https://raw.githubusercontent.com/AnacondaRecipes/neuralprophet-feedstock/e4fdc4721cc63cf1c4dc433dba1fcf865677a7ab/recipe/fix_scripts.patch
2. AnacondaRecipes PR https://github.com/AnacondaRecipes/neuralprophet-feedstock/pull/1

**Comment by ourownstory** [comment]
Hi @skupr-anaconda 
Thank you for the clear issue.

Do you mind clarifying, whether you are intending to install the developer/contributor version `neuralprophet["dev"]` including optional packages and git hooks? The script `neuralprophet_dev_setup` is not needed for regular installs and can be ignored.

However, I assume that simply it's existence, despite it not being called is the stumbling block for anaconda?
I am not an anaconda user, so clarifications are welcome.

**Comment by ourownstory** [comment]
@skupr-anaconda Would you like to give us some pointers how we can add a proper CI test for anaconda builds, so we can avoid these kind of issues in the future?

**Comment by ourownstory** [comment]
@skupr-anaconda merged. Lmk if this resolves the issue?

Btw, dataclasses package install has now also been reduced to `python_version<'3.7'`

**Comment by skupr-anaconda** [comment]
The script `neuralprophet_dev_setup` installs by default from the pypi source file by pip and setuptools. If this script can be ignored then I think an appropriate logic in setup.py should be implemented.
There is no need for the additional CI test. 

@ourownstory And thank you that you fixed installing dataclasses with python <3.7, I'll update my recipe

**Comment by ourownstory** [comment]
> The script `neuralprophet_dev_setup` installs by default from the pypi source file by pip and setuptools. If this script can be ignored then I think an appropriate logic in setup.py should be implemented. There is no need for the additional CI test.

Based on my understanding, it is provided/installed, but not called/run during a pip install, unless explicitly called by the user. 
Is this different with anaconda or am I missing something?

> @ourownstory And thank you that you fixed installing dataclasses with python <3.7, I'll update my recipe

Credit goes to @gkanapathy for #606.

**Comment by ourownstory** [comment]
@skupr-anaconda It should be fine, as the scripts are just for git hooks. As long as no errors occur, it shouldn't matter.
