### ISSUE TITLE
Including n_lags>0 in the model gives only 1 forecasted value

### ISSUE THREAD

**Issue by atanuray099** [ourownstory/neural_prophet#622]
While adding n_lags(>0) along with other parameters in NeuralProphet model results in only 1 forecasted value while we are targeting for 52 forecasted values(n_forecasts=52).

Is there any particular reason for this , as when we are using n_lags=0, it is working perfectly !!!!

**Comment by ourownstory** [comment]
Hi @atanuray099 
did you set `n_forecasts=52` in the model definition?

if so,, please provide a minimal code snippet that reproduces the error.

Thank you!
