### ISSUE TITLE
neural prophet  test the validate data

### ISSUE THREAD

**Issue by Man1978-scd** [ourownstory/neural_prophet#626]
I use the test function to do cross validation
`metrics_train = m.fit(df=df_train, freq="MS")
metrics_test = m.test(df=df_test)`
the result is show the MAE and RMSE, where is the predict result? that means the yhat value,how to get?

**Comment by bhausleitner** [comment]
Hi @Man1978-scd,

thank you for reaching out and creating this issue. 

``metrics_train`` and ``metrics_test`` are the respective dataframes that contain the error metrics for your fitting process. Unlike specified, these metrics are per default set to ``MAE`` and ``RMSE``, feel free to find more info on the documentation for the variable ``collect_metrics``: https://neuralprophet.com/html/forecaster.html

You can obtain the ``y_hat`` by calling: 

`y_hat = m.predict(df)` 

where ``m`` is your previously fitted model. 

Let me know if this helps and feel free to reach out at any time!

**Comment by Man1978-scd** [comment]
> Hi @Man1978-scd,
> 
> thank you for reaching out and creating this issue.
> 
> `metrics_train` and `metrics_test` are the respective dataframes that contain the error metrics for your fitting process. Unlike specified, these metrics are per default set to `MAE` and `RMSE`, feel free to find more info on the documentation for the variable `collect_metrics`: https://neuralprophet.com/html/forecaster.html
> 
> You can obtain the `y_hat` by calling:
> 
> `y_hat = m.predict(df)`
> 
> where `m` is your previously fitted model.
> 
> Let me know if this helps and feel free to reach out at any time!

Thank you very much for your answer, the predict function needs to specify the y value, which is different from Prophet, I assume that I don't know the y value of the test set, then I use `make_future_dataframe` to make predictions, and then calculate the value of MAE by myself, this value is not same as using The` m.test` method , for example, i set `n_lags=10`, predict 100 values in the future, first ,i predict 10 result, and then I append these 10 values to traindata, reuse `make_future_dataframe` , and finally I can get 100 values, this result is not the same as the `m.test` method, if i set `n_lags=`100, the prediction effect is very poor, not an ideal parameter

**Comment by Man1978-scd** [comment]
> Hi @Man1978-scd,
> 
> thank you for reaching out and creating this issue.
> 
> `metrics_train` and `metrics_test` are the respective dataframes that contain the error metrics for your fitting process. Unlike specified, these metrics are per default set to `MAE` and `RMSE`, feel free to find more info on the documentation for the variable `collect_metrics`: https://neuralprophet.com/html/forecaster.html
> 
> You can obtain the `y_hat` by calling:
> 
> `y_hat = m.predict(df)`
> 
> where `m` is your previously fitted model.
> 
> Let me know if this helps and feel free to reach out at any time!
