### ISSUE TITLE
NaNs when predicting with future regressors

### ISSUE THREAD

**Issue by yanirs** [ourownstory/neural_prophet#627]
**Prerequisites**

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in a new virtualenv with only neuralprophet installed, directly from github:
      ```shell
      git clone <copied link from github>
      cd neural_prophet
      pip install .
      ```
    * Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
      If you have the same question but the Answer does not solve your issue, please continue the conversation there.
    * Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
      If you have the same issue but there is a twist to your situation, please add an explanation there.
    * Considered whether your bug might actually be solveable by getting a question answered: 
      * Please [post a package use question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-get-help-using-neuralprophet)
      * Please [post a forecasting best practice question](https://github.com/ourownstory/neural_prophet/discussions/categories/q-a-forecasting-best-practices)
      * Please [post an idea or feedback](https://github.com/ourownstory/neural_prophet/discussions/categories/ideas-feedback)

**Describe the bug**

When predicting for the same period with and without future regressors, there are some NaNs predicted for periods for which the model should be able to produce forecasts.

**To Reproduce**

See example:

```python
In [1]: import pandas as pd

In [2]: import numpy as np

In [3]: import neuralprophet

In [4]: demo_df = pd.DataFrame(
   ...:     {
   ...:         "ds": pd.date_range("2022-04-01", "2022-04-30"),
   ...:         "y": np.random.random(30),
   ...:         "reg": np.random.random(30),
   ...:     }
   ...: )

In [5]: demo_model = neuralprophet.NeuralProphet(epochs=1, n_forecasts=3, n_lags=6)
   ...: demo_model.add_future_regressor("reg")
   ...: demo_model.fit(demo_df)
   ...: demo_model.predict(demo_df).tail(1)

Out[5]: 
           ds         y yhat1 residual1 yhat2 residual2     yhat3 residual3   ar1   ar2       ar3     trend season_weekly future_regressors_additive future_regressor_reg
29 2022-04-30  0.506658  None       NaN  None       NaN  1.245905  0.739247  None  None -0.150866  1.219648      1.219425                  -1.042303            -1.042303

In [6]: demo_model = neuralprophet.NeuralProphet(epochs=1, n_forecasts=3, n_lags=6)
   ...: demo_model.fit(demo_df[["ds", "y"]])
   ...: demo_model.predict(demo_df[["ds", "y"]]).tail(1)

Out[6]: 
           ds         y    yhat1 residual1     yhat2 residual2    yhat3 residual3      ar1       ar2       ar3     trend season_weekly
29 2022-04-30  0.506658  1.02169  0.515032  1.220214  0.713556  2.25736  1.750701  0.05825  0.256773  1.293918  0.415311       0.54813
```

**Expected behavior**

I expected to see predictions for all the dates in `demo_ds` for both models (with and without `reg` as a future regressor). For example, I don't see why `yhat1` for 2022-04-30 would be `None` when using the future regressor `reg`, as the value for 2022-04-30 is known.

**What actually happens**

See example.

**Environement (please complete the following information):**

 - Python environment: Python 3.9, in standalone venv with no other packages
 - NeuralProphet version and install method: Installed directly from GitHub as in the instructions above (commit: https://github.com/ourownstory/neural_prophet/commit/dfa376a8a7ff7d7a280825f304b6471a79319027).

**Additional context**

From poking around, it looks like the problem is that `NeuralProphet._maybe_extend_df()` doesn't extend the DF if there are regressors.

**Comment by yanirs** [comment]
Hmm... Maybe I misunderstood the meaning of future regressors. Are their values supposed to be known `n_forecasts` into the future? If so, it'd be good to note that in the docs.

**Comment by bhausleitner** [comment]
Hey @yanirs, thank you so much for flagging this! The value of future regressors has to be known for ``n_forecasts``into the future. I will add this to the docs. Thanks again for flagging this!

**Comment by bhausleitner** [comment]
@yanirs I just created this PR, feel free to review if this documentation fits your needs! 

https://github.com/ourownstory/neural_prophet/pull/628

cc @ourownstory

**Comment by yanirs** [comment]
Thanks for the quick response, @bhausleitner! I left a couple of comments on the PR.

**Comment by bhausleitner** [comment]
Hi @yanirs, thanks for the comments. I've incorporated your notes and merged the respective PR into the main branch. The changes will be reflected shortly on the documentation website. 

Again, thanks for your contribution! We highly appreciate your support :)
