### ISSUE TITLE
epochs arg in fit()

### ISSUE THREAD

**Issue by zisismp4** [ourownstory/neural_prophet#632]
I keep getting an error when using the fit() function.. Seems epochs arg is not recognized. 

TypeError: fit() got an unexpected keyword argument 'epochs'

**Comment by bhausleitner** [comment]
Hi @zisismp4, 

thanks for flagging this. Do you mind sharing a minimal example of your code? What model specifications are you using? 

Thanks!

**Comment by zisismp4** [comment]
Take a look:

m = NeuralProphet(daily_seasonality=True)
m.fit(data[1:],freq='D',epochs=1000)

TypeError: fit() got an unexpected keyword argument 'epochs'

I am trying to learn neuralprophet and I actually encounter the same problem in every online tutorial (e.g. https://colab.research.google.com/github/iannjari/neuralprophet/blob/main/NeuralProphet.ipynb#scrollTo=tgGa9h5GB29A )

**Comment by bhausleitner** [comment]
Hi @zisismp4, 

thanks for your reply again! And thank you for providing a minimal example of your code. 

We recently deprecated the definition of the argument ``epochs`` in the ``fit()`` method. 

Instead, please call epochs in the main Initialisation of the NeuralProphet model ``m``. See example below: 

`m = NeuralProphet(daily_seasonality=True, epochs=1000)
m.fit(data[1:],freq='D')` 

Let us know if this helps! And again, thank you so much for flagging this, we will make it more clear in the documentation! 

Best,
Berni

cc @ourownstory

**Comment by ourownstory** [comment]
@zisismp4 Sorry for the trouble! Please let us know if this works for your usecase, or if you require it in fit?

**Comment by zisismp4** [comment]
@ourownstory Yeah it works fine!
