### ISSUE TITLE
Add GPU support

### ISSUE THREAD

**Issue by kapoor1992** [ourownstory/neural_prophet#662]
**Is your feature request related to a problem? Please describe.**

Yes. Training times can be slow.

**Describe the solution you'd like**

GPU support.

**Describe alternatives you've considered**

Reducing data size isn't an option in my case.

**Additional context**

This thread is old so I'd like an update please: https://github.com/ourownstory/neural_prophet/discussions/408

FYI @dawolfgang

**Comment by karl-richter** [comment]
Resolved with the introduction of lightning, GPU is now supported.
