### ISSUE TITLE
CodeQL Github Action Integration v1 expires in December 2022

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#667]
Read details here: https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/

Required changes
- Upgrade Github Action for CodeQL to v2 before December 2022
- Template for CodeQL Github Action with latest version: https://github.com/github/codeql-action#usage

Should be a simple change, happy to help with a contribution.

**Comment by ourownstory** [comment]
@noxan I was considering to drop this altogether, as it takes a long time, and as the package does not connect to the internet. Or do you think that v2 brings enough of a speed-up that it may be worth keeping?

**Comment by noxan** [comment]
@ourownstory I could give it a try and see the effect. Otherwise how about integrating linters like flake8, isort, and possibly black in case we want unified code formatting?

**Comment by noxan** [comment]
Fixed by commit https://github.com/ourownstory/neural_prophet/commit/534f8029fd852223b1234d2e4036db0cef02bb90
