### ISSUE TITLE
[feature] Mask seasonality on Sat/Sun when data frequency is Business days.

### ISSUE THREAD

**Issue by Haridut** [ourownstory/neural_prophet#706]
Is there a way to pass in a data frame without weekends for prediction? The predict function seems to be working only when we use make future data frame function and not when we use external data which doesn’t have weekends.

**Comment by ourownstory** [comment]
Hi @Haridut 
Have you tried setting the frequency to "B" for business days only?

Yes, the data format for training and predicting should be the same.

**Comment by erykml** [comment]
Using the "b" flag worked for me. 
@ourownstory, if I can hijack the question, is there a way to disable the intra-week seasonality when using business days? So when using business days, the seasonality is only calculated for the business days, and you would not see the Sat and Sun in the components plots.

**Comment by ourownstory** [comment]
@erykml 
That is a great suggestion. We have not implemented such a masking, as there are many possible such special cases.
However, Business days may be a prominent enough edge case to warrant a special masking. 
Would you like to contribute this feature?
