### ISSUE TITLE
Inconsistent weekly seasonality produced by NeuralProphet plot_components

### ISSUE THREAD

**Issue by nlaptev** [ourownstory/neural_prophet#71]
![Screen Shot 2020-09-17 at 8 03 18 AM](https://user-images.githubusercontent.com/8388935/93489390-53b2fa80-f8bc-11ea-91c1-168c7b6fbb88.png)

**Comment by nlaptev** [comment]
See attached image

**Comment by ourownstory** [comment]
@nlaptev Can you please check if the issue is resolved now?
You could also contribute a test cast to replicate your issue.
