### ISSUE TITLE
Harmonize internal event and holiday implementation

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#712]
Holidays are only a special kind of events, yet events and holidays often have two almost the same implementations. This issue's aim is to harmonize the implementations and only have a single generic implementation, removing almost duplicate code.

More information and details to follow.

**Comment by leoniewgnr** [comment]
Can I work on this?

**Comment by leoniewgnr** [comment]
This is done:) Would be great if anyone could link the pull request #1110 to this issue
