### ISSUE TITLE
pandas throws ValueError when setting raw=True in predict function

### ISSUE THREAD

**Issue by f-izzat** [ourownstory/neural_prophet#721]
**Describe the bug**

Inside NeuralProphet.__convert_raw_predictions_to_raw_df, creating a new data frame `df_raw` requires a 2D input

**To Reproduce**

```
from neuralprophet import NeuralProphet, set_log_level
set_log_level("ERROR")
data_location = "https://raw.githubusercontent.com/ourownstory/neuralprophet-data/main/datasets/"
df = pd.read_csv(data_location + "wp_log_peyton_manning.csv")
m = NeuralProphet(
    quantiles=[0.9, 0.1]
)
metrics = m.fit(df, freq="D")
future = m.make_future_dataframe(df, periods=30, n_historic_predictions=100)
forecast = m.predict(df=future, raw=True)

```

**Screenshots**

![image](https://user-images.githubusercontent.com/97789955/185295409-132b0f0e-6f4e-46cb-b97e-a3703f8a9111.png)

**Environement**
Python Version: 3.7
NeuralProphet version: 0.3.3
Pandas version: 1.3.5

**Comment by judussoari** [comment]
Thanks for creating the Issue @f-izzat 
I proposed a solution which is currently under review.
