### ISSUE TITLE
How can I use the Simple Uncertainty estimation? And "__init__() got an unexpected keyword argument 'quantiles'" error occur.

### ISSUE THREAD

**Issue by HopeWorld218** [ourownstory/neural_prophet#727]
Hello Neural_prophet teams,
   I would like to use NeuralProphet  to detect anomaly points in time series which need an overall uncertaincy. In fbProphet, the yhat_lower and yhat_upper can be used to achieve my goal. And in your development_timeline.md, I see it can use **Simple Uncertainty estimation** now. How should I use it?
    And in your tutorial, I see ` NeuralProphet(quantiles=[0.9, 0.1])` . But when I run in my Jupyter notebook, it reported **__init__() got an unexpected keyword argument 'quantiles'.**. And I try three ways to install NeuralProphet `pip install git+https://github.com/ourownstory/neural_prophet.git` `pip install neuralprophet[live]` but the error above also exist.
    Thanks for your working. I hope I can get your apply soon.

**Comment by ourownstory** [comment]
Hi @HopeWorld218 
Thank you for the question.
What you are attempting should be possible.

I think you are installing version 0.3.2 which does not support quantiles yet.
When you use `pip install neuralprophet[live]` it retrieves the pip version (0.3.2), not the github version.
Check what `neuralprophet.__version__` returns.

Hope this resolves it. feel free to reopen the issue if not.

**Comment by HopeWorld218** [comment]
I ues this way to install package And the version is 0.3.3. The problem seems not be resolved
![image](https://user-images.githubusercontent.com/58178735/186323989-fdf9b4e8-bf51-4f0b-953d-69c0c38c8b80.png)

**Comment by HopeWorld218** [comment]
Sorry， I can not reopen the issue closed by others.

**Comment by HopeWorld218** [comment]
> Hi @HopeWorld218 Thank you for the question. What you are attempting should be possible.
> 
> I think you are installing version 0.3.2 which does not support quantiles yet. When you use `pip install neuralprophet[live]` it retrieves the pip version (0.3.2), not the github version. Check what `neuralprophet.__version__` returns.
> 
> Hope this resolves it. feel free to reopen the issue if not.

Sorry， I can not reopen the issue closed by others.
