### ISSUE TITLE
[bug] Unsqueeze quantile dimension to match multiplied tensor

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#735]
fitting the model with quantiles produces this warning:
`WARNING - (py.warnings._showwarnmsg) - /home/studio-lab-user/.conda/envs/dev/lib/python3.9/site-packages/torch/nn/modules/loss.py:921: UserWarning: Using a target size (torch.Size([32, 1, 1])) that is different to the input size (torch.Size([32, 1, 3])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.smooth_l1_loss(input, target, reduction=self.reduction, beta=self.beta)`

Though it does not cause harm, it is better to explicitly match dimensions instead of broadcasting.

**Comment by ourownstory** [comment]
A similar warning is returned by a test:
```
tests/test_unit.py::test_add_lagged_regressors
  /home/tabletop/venv/np-dev/lib/python3.10/site-packages/torch/nn/modules/loss.py:922: UserWarning:
  
  Using a target size (torch.Size([97])) that is different to the input size (torch.Size([97, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
```

**Comment by karl-richter** [comment]
Will be adressed by #1159.
