### ISSUE TITLE
Change str.format() to f-string throughout the neuralprophet source code

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#755]
For example: 

`log.info("{} NaN values in column {} were auto-imputed.".format(sum_na - remaining_na, column))`
--> 
`log.info(f"{sum_na - remaining_na} NaN values in column {column} were auto-imputed.")`

This makes the code more readable as well as saves some space.

**Comment by Ben-Ostrovsky** [comment]
Hey Kevin, I would love to help with this issue! Which .py files in neuralprophet should be edited?

**Comment by Kevin-Chen0** [comment]
Yea that will be great Ben! Ideally, all of the files in the **neuralprophet/** folder. Please look at the Contribute page [here](https://github.com/ourownstory/neural_prophet/blob/main/CONTRIBUTING.md) if it is your first time. Thx!
