### ISSUE TITLE
Trend Regularization: Find better way to regularize

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#8]
Needed for better learning of trend deltas without gradient bleedover to older trend delta parameters. This is important if we want to achieve proper automatic trend-changepoint detection.

**Comment by ourownstory** [comment]
likely not the solution but worth considering: penalize changepoints as sum of diff to previous and next segment
analogous to reg term of Hodrick–Prescott_filter

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
