### ISSUE TITLE
[enhancement]  remove regressor if training set has one unique value

### ISSUE THREAD

**Issue by ourownstory** [ourownstory/neural_prophet#813]
Instead of throwing an error, simply remove the problematic regressor from the model with an error log message.
https://github.com/ourownstory/neural_prophet/blob/ea717ad31dec216ba670492f9b89fd075621dc3a/neuralprophet/df_utils.py#L318

This has caused issues for people in the past.
e.g. #809

This  must also address:
- reduce error to warning when unused column in df ( training or predicting have unused cols not in model definition)

**Comment by karl-richter** [comment]
Note: we discussed that we would simply remove a regressor with non-unique values from the model and throw a warning instead of manipulating the models weights.
