### ISSUE TITLE
[enhancement] Easy access and display of the NeuralProphet parameters (either as string print-out or dict)

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#821]
Add `m.summary()` (from [Keras](https://keras.io/api/models/model/#summary-method)), `m.state_dict()` (from [PyTorch](https://pytorch.org/tutorials/recipes/recipes/what_is_state_dict.html)), and/or `m.parameters()` (also from PyTorch) methods into the NeuralProphet module.

This makes it easier to show and port the NeuralProphet parameters, including for seasonality, lags, changepoints, and others.

**Comment by Kevin-Chen0** [comment]
Use `m.state_dict()` for display the NeuralProphet hyperparameters in the dictionary format.

**Comment by noxan** [comment]
Seems to be related to #252 and its pull request #935
