### ISSUE TITLE
See if we can autofix with Github actions or otherwise add git hooks locally

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#835]
For isort, black and flake8

**Comment by karl-richter** [comment]
@noxan as you mentioned yourself, I am not sure if its a good idea to run formatting in a gh action since it creates commits by a bot (which reduce traceability). Since all of us should use black locally, I guess it should be rare that the test failes...lets discuss on that.

**Comment by noxan** [comment]
Closing as this might not be a good thing
