### ISSUE TITLE
NeuralProphet with numba

### ISSUE THREAD

**Issue by tulbureandreit** [ourownstory/neural_prophet#848]
TLDR: Has anybody used numba to speed up neuralprophet? And other pytorch based code ? If yes, does it work?

My concern is that since I added lags and regressors, the neural prophet compute got VERY slow and it takes 10 hours to loop over 700 products on which I want to do forecasting on.

Any help is great!

Thanks!

**Comment by ourownstory** [comment]
Hi @tulbureandreit did you add a large number of regressors?
We are currently working on vectorizing that area of code.

**Comment by ourownstory** [comment]
I would love to hear if anyone has had any success with numba!

**Comment by noxan** [comment]
@tulbureandreit we'll look into it with the other issue, glad to have your input :)
