### ISSUE TITLE
Project dependencies may have API risk issues

### ISSUE THREAD

**Issue by PyDeps** [ourownstory/neural_prophet#911]
Hi, In **neural_prophet**, inappropriate dependency versioning constraints can cause risks.

Below are the dependencies and version constraints that the project is using

```
numpy>=1.15.4
pandas>=1.0.4
matplotlib>=2.0.0
torch>=1.8.0
LunarCalendar>=0.0.9
convertdate>=2.1.2
holidays>=0.11.3.1
python-dateutil>=2.8.0
tqdm>=4.50.2
torch-lr-finder>=0.2.1
ipywidgets>=7.5.1
plotly>=4.14.3
dataclasses>=0.6;python_version<'3.7'
```

The version constraint **==** will introduce the risk of dependency conflicts because the scope of dependencies is too strict.
The version constraint **No Upper Bound** and **\*** will introduce the risk of the missing API Error because the latest version of the dependencies may remove some APIs.

After further analysis, in this project,
The version constraint of dependency **matplotlib** can be changed to *>=1.4.0,<=3.0.3*.
The version constraint of dependency **holidays** can be changed to *>=0.2,<=0.14.2*.
The version constraint of dependency **python-dateutil** can be changed to *>=2.1,<=2.8.2*.
The version constraint of dependency **tqdm** can be changed to *>=4.36.0,<=4.64.0*.

The above modification suggestions can reduce the dependency conflicts as much as possible, 
and introduce the latest version as much as possible without calling Error in the projects.

The invocation of the current project includes all the following methods.

<details><summary>The calling methods from the matplotlib</summary>
 <pre>matplotlib.dates.MonthLocator
matplotlib.dates.num2date
matplotlib.dates.AutoDateLocator
matplotlib.dates.AutoDateFormatter
matplotlib.ticker.FuncFormatter
</pre>
</details>
<details><summary>The calling methods from the holidays</summary>
 <pre>holidays.HolidayBase.__init__
</pre>
</details>
<details><summary>The calling methods from the python-dateutil</summary>
 <pre>dateutil.relativedelta.relativedelta
dateutil.easter.easter
</pre>
</details>
<details><summary>The calling methods from the tqdm</summary>
 <pre>tqdm.tqdm
</pre>
</details>
<details><summary>The calling methods from the all methods</summary>
 <pre>plot_custom_season
events_df.copy.reset_index
i.self.ar_net
neuralprophet.plot_forecast_plotly.plot_components
df.reset_index.copy
self.compute.pd.DataFrame.to_string
f.read
m.model.get_reg_weights
df.ds.isin
neuralprophet.df_utils.make_future_df
numpy.random.choice
get_dist_considering_two_freqs
threshold_time_stamp.df_i.df_i.len.df_i.copy.iloc.reset_index
torch.cos.time
torch.nn.ParameterDict
self._loss_fn
reserved_names.extend
kwargs.items
targets.np.array.np.isnan.any
value.detach.numpy.items
targets.detach.squeeze
torch.utils.data.DataLoader
df.reset_index.isna
data.append
m.predict_seasonal_components.squeeze
get_multiforecast_component_props
traces.append
self._convert_raw_predictions_to_raw_df
fig.add_subplot.plot
torch.maximum
m.set_shift_scale
neuralprophet.utils.set_auto_seasonalities
config_regressor.keys
country.pyholidays.getattr
df_name.other_df.other_df.reset_index
comp.keys
numpy.mean
torch.cat
numpy.unique
split_idx.df_fold.iloc.reset_index
torch.log
self._handle_missing_data.drop
neuralprophet.configure.from_kwargs
self.config_train.get_optimizer
sorted.append
self.stored_values.append
pandas.concat
self._evaluate_epoch.items
create_event_names_for_offsets
df_v.copy
self.metrics.reset
config_covariates.keys
Exception
dt.values.nonzero.dt.iloc.min
covariates.keys
get_normalization_params
col.df.sum
reg_ar.torch.sum.squeeze
inputs.items
self.season_dims.items
self.config_train.loss_func
self.trend
self.trend_m.unsqueeze
plotly.graph_objs.scatter.Line
neuralprophet.configure.Normalization
self.bias.unsqueeze
comp_name.fcst.notna.fillna
self.PinballLoss.super.__init__
numpy.argsort
merge_dataframes
self._handle_missing_data
self.quantiles.torch.tensor.unsqueeze.unsqueeze
torch.zeros_like
self._train
targets.detach
torch.optim.AdamW
neuralprophet.custom_loss_metrics.PinballLoss
value.detach
comp_name.fcst.notna.head
h.setLevel
neuralprophet.plot_model_parameters.predict_one_season
neuralprophet.metrics.LossMetric
torch.cos
m.model.trend_k0.detach
self.auto_regression
logging.getLogger.setLevel
convertdate.islamic.from_gregorian
enumerate
fig.add_subplot.grid
lagged_scalar_regressors.append
make_events_features
logging.StreamHandler
self.loss_func.lower
name.lower
self.layers
self.LossMetric.super.__init__
plotly.graph_objs.layout.YAxis
comp.lower.startswith
self._handle_missing_data.copy
os.path.dirname
open
ShiftScale
self.model.train
ax.xaxis.set_major_formatter
plot_daily
plotly.subplots.make_subplots.update_layout
dt.values.nonzero
df.reset_index.select_dtypes
additive_events.columns.tolist
data_params.df_i.df_utils.normalize.copy
avg_value.data.item
self.trend_deltas.unsqueeze
m.config_regressors.items
torch.unsqueeze
range.set_postfix
self.metrics.get_stored_as_df
name.predicted.append
multiplicative_regressors.columns.tolist
comp_name.fcst.notna.count
logger.debug
self.compute
plot_yearly
plot_forecast_component
range
neuralprophet.plot_model_parameters.plot_daily
torch_lr_finder.LRFinder
neuralprophet.utils.config_regressors_to_model_dims
torch.div
tabularize_univariate_datetime
neuralprophet.df_utils.add_missing_dates_nan
get_dynamic_axis_range
plotly.subplots.make_subplots
split_idx.df_merged.reset_index
df_i.copy.reset_index
loc.self.get_stored_as_df.to_string
neuralprophet.df_utils.return_df_in_original_format
get_freq_dist
param.detach.numpy
_crossvalidation_split_df
tqdm.tqdm
fcst.dt.hour.all
matplotlib.dates.AutoDateFormatter
join
df.reset_index.set_index
livelossplot.PlotLosses.send
col.df.isnull
sys.stdout.close
torch.optim.SGD
set_logger_level
values.append
torch.nn.init.xavier_normal_
numpy.sum
self._prepare_dataframe_to_predict
t.self.model.trend.detach
torch.where
self._reshape_raw_predictions_to_forecst_df
float
convertdate.islamic.to_gregorian
df.loc.isnull.any
mask.df_i.copy.drop
m.predict_seasonal_components
merge_dataframes.drop_duplicates
self.covariate
neuralprophet.df_utils.normalize
neuralprophet.utils.set_y_as_percent.get_figure
torch.nn.SmoothL1Loss
self._add_batch_regularizations
convert_events_to_features
self.FlatNet.super.__init__
numpy.concatenate.items
fcst_t.strftime.fcst_t.strftime.pd.date_range.to_pydatetime
name.m.model.get_covar_weights.detach.numpy
df_name.fcst.fcst.copy.notna
numpy.sqrt
gammas.unsqueeze
df.unique
dims.torch.randn.torch.nn.init.xavier_normal_.squeeze
quantile_index.m.model.get_trend_deltas.detach.numpy.squeeze
abs_weights.torch.sum.torch.mean.squeeze
self.trend_k0.unsqueeze.unsqueeze
math.isclose
df.copy.diff
self.__class__
quantile_index.m.model.bias.detach.numpy.squeeze
plot_scalar_weights
col_name.startswith
max
pandas.plotting.deregister_matplotlib_converters
neuralprophet.utils.symmetric_total_percentage_error
columns.extend
ds_col.pd.to_datetime.view
fig.add_subplot.set_xticks
self.local_data_params.keys
collections.OrderedDict
t.unsqueeze.sum
torch.nn.Linear
auto_normalization_setting
df_name.local_data_params.items
neuralprophet.metrics.MetricsCollection
matplotlib.pyplot.figure.add_subplot
m.model.bias.detach
self.layers.append
neuralprophet.utils.reg_func_events
series.interpolate.rolling
name.m.model.get_covar_weights.detach
neuralprophet.df_utils.check_dataframe
self._init_model
numpy.column_stack
lunarcalendar.Converter.Lunar2Solar
fcst.dt.to_pydatetime
self.trend_deltas.unsqueeze.unsqueeze
df.copy.unique
inspect.signature
numpy.zeros_like
torch.nn.MSELoss
t.unsqueeze
self._handle_missing_data.reset_index
self.ValueMetric.super.__init__
pandas.to_timedelta
exec
logging.getLogger.debug
weights.torch.abs.torch.mean.squeeze
self.all_seasonalities.items
neuralprophet.df_utils.merge_dataframes
neuralprophet.configure.Holidays
self.model.seasonality
m.update
reg_func_abs
df_name.fcst.fcst.copy.unique
self.batch_metrics.append
setuptools.setup
numpy.std
torch.load
fcst.fillna.count
self.all_covariates
datetime.datetime.dates.dt.total_seconds.astype
neuralprophet.df_utils.fill_linear_then_rolling_avg
m.compute
specific_metrics.append
torch.nn.functional.one_hot.unsqueeze
warnings.filterwarnings
m.model.seasonality
numpy.delete.max
range.set_description
logging.getLogger
t_end.t_start.pd.Series.dt.to_pydatetime
self.DeepNet.super.__init__
m.model.bias.detach.numpy
numpy.log
quantile_index.t.self.model.trend.detach.numpy.squeeze
self.get_stored
events.keys
target.repeat.repeat
torch.nn.Sequential
collections.OrderedDict.keys
num_overplot.comp_name.fcst.notna
self.ar_net.append
self.config_regressors.items
pandas.Series.shift
config_events.items
subprocess.call
split_df
regressor_param.detach.numpy
optimizer_name.lower
inputs.keys
_stride_time_features_for_forecasts
series.interpolate.isnull
neuralprophet.utils.print_epoch_metrics.splitlines
torch.optim.lr_scheduler.OneCycleLR
matplotlib.pyplot.figure.tight_layout
check_single_dataframe
make_country_specific_holidays_df.keys
pandas.to_datetime
self.inputs.items
NotImplementedError
m.model.get_covar_weights
activation
logging.FileHandler
plotly.graph_objs.Scatter
numpy.squeeze
numpy.isinf
neuralprophet.utils.set_y_as_percent
key.self.inputs.items
plot_weekly
additive_events_dims.sort_values.reset_index.sort_values
torch.no_grad
country.hdays_part1.getattr.items
additive_regressor_feature_windows.append
dateutil.relativedelta.relativedelta
neuralprophet.utils_torch.lr_range_test
self.value_metrics.values
pandas.merge
config_regressors.items
fcst.fillna.head
ax.set_yticklabels
numpy.floor
_crossvalidation_with_time_threshold
value.items
torch.nn.ModuleList
torch.nn.ModuleList.append
predicted.detach.numpy
fun
numpy.array
m.reset
df.reset_index.sort_values
df_i.copy.pd.to_datetime.sort_values
data.np.array.np.isnan.any
self.seasonality
neuralprophet.utils_torch.create_optimizer_from_config
AttributeError
m.new
create_optimizer_from_config
self.TimeNet.super.__init__
cls
n_lower_quantiles.diffs.unsqueeze.repeat.detach
callable
pathlib.Path
neuralprophet.plot_forecast.plot
regressors.keys
make_country_specific_holidays_df
tuple
self._make_future_dataframe
df_i.copy.pd.to_datetime.sort_values.max
neuralprophet.time_dataset.GlobalTimeDataset
multiplicative_event_feature_windows.append
setuptools.find_packages
df.copy.dropna.pd.to_datetime.sort_values.max
name.component_vectors.append
seasonal_features_from_dates
torch.nn.functional.one_hot
torch.nn.L1Loss
sorted
zip
comp.update
name.df.loc.notnull
self.trend_changepoints_t.unsqueeze
neuralprophet.configure.Regressor
events_df.copy.reset_index.copy
params.unsqueeze
fig.add_subplot.set_xticklabels
self.MSE.super.__init__
pandas.isna
logging.getLogger.addHandler
torch.from_numpy
m.model.get_event_weights.items
series.interpolate.interpolate
df_name.df.df.min
df_name.fcst.fcst.copy
components.append
torch.abs
split_considering_timestamp
neuralprophet.df_utils.prep_or_copy_df
self.regressors_dims.items
plotly.graph_objs.Figure
data.items
name.df.loc.values.np.isinf.any
model.get_event_weights.keys
df.loc.astype
torch.sum.detach
sphinx.ext.autodoc.between
diffs.unsqueeze.repeat
nan_at_end.df.iloc.ffill
self.events_dims.items
matplotlib.ticker.FuncFormatter
predicted.squeeze.detach
inspect.isclass
torch.ones_like
df.reset_index.groupby
matplotlib.pyplot.subplots
rolling.comp_name.fcst.rolling.mean
self.metrics.add_specific_target
pandas.DataFrame
convert_num_to_str_freq
neuralprophet.utils.set_y_as_percent.set_ylabel
pandas.infer_freq
plotly.graph_objs.layout.Margin
r.df.set_index.reindex.rename_axis.reset_index
neuralprophet.configure.Event
getattr
hasattr
collect_metrics.lower
pandas.to_numeric
self.all_seasonalities
_stride_lagged_features
df.reset_index.reset_index
torch.minimum
neuralprophet.metrics.MetricsCollection.get_stored_as_df
m.predict_season_from_dates
self.model.eval
ds_col.pd.to_datetime.view.diff
livelossplot.PlotLosses
plot_lagged_weights
neuralprophet.utils.fcst_df_to_last_forecast
self._eval_true_ar
df.reset_index.items
optimizer_name
df_raw.merge.merge
collections.OrderedDict.items
config_covar.items
logger.error
n_upper_quantiles.diffs.unsqueeze.repeat.detach
fig.add_subplot.get_xticklabels
self._piecewise_linear_trend
fcst.head.to_string
numpy.isnan
additive_event_feature_windows.append
neuralprophet.df_utils.handle_negative_values
self._init_val_loader
ahead.format.fcst.count
name.df.sub
m.config_events.items
year.date.weekday
values.keys
torch.clamp
m.model.ar_weights.detach
all
feature_tutorial.endswith
self._update_batch_value
neuralprophet.utils.set_y_as_percent.set_xlabel
os.listdir
collections.defaultdict
new_param
livelossplot.PlotLosses.update
ax.xaxis.set_major_locator
fig.add_subplot.bar
neuralprophet.utils.set_y_as_percent.bar
lrs.append
data_columns.append
self.config_season.append
neuralprophet.time_dataset.make_country_specific_holidays_df
self.update_batch
os.path.abspath
plotly.graph_objs.layout.YAxis.update
years.country.hdays_part2.getattr.values
neuralprophet.time_dataset.TimeDataset
self.model.season_params.keys
torch.sum
fcst.fillna.notna
other_df.drop.copy
self.set_quantiles
self.config_ar.regularize
app_tutorial.endswith
df.copy.max
isinstance
years.country.pyholidays.getattr.values
predict_one_season
len
numpy.nan_to_num
value.detach.numpy
names.append
fcst.fillna.fillna
matplotlib.pyplot.figure
pandas.DataFrame.to_string
m.model.ar_weights.detach.numpy
plotly.graph_objs.layout.yaxis.Title
numpy.empty_like
df.columns.df_i.loc.copy
predicted.numpy.numpy
crossvalidation_split_df
predict_season_from_dates
logging.getLogger.info
df.copy.min
make_regressors_features
losses.np.array.argmin
weights.torch.abs.pow
df.copy.dropna.pd.to_datetime.sort_values
comp.yhat.pd.Series.set_axis
neuralprophet.time_dataset.fourier_series
issubclass
m.lower
df_raw.merge.insert
torch_lr_finder.LRFinder.plot
self.BatchMetric.super.__init__
self.RMSE.super.__init__
self._evaluate
targets_dtype.targets.torch.from_numpy.type.unsqueeze
get_parameter_components
offset.year.Lunar.Converter.Lunar2Solar.to_date
torch.tensor
torch_lr_finder.LRFinder.range_test
datetime.datetime
neuralprophet.utils.set_y_as_percent.fill_between
out.write
m.model.trend_k0.detach.numpy
data_params_definition.items
m.lower.METRICS
__file__.pathlib.Path.parent.parent.absolute
get_seasonality_props
self.trend_k0.unsqueeze
gammas.unsqueeze.unsqueeze
config_events.keys
_infer_frequency
torch.randn
columns.append
torch.utils.data.Subset
numpy.cos
self.metrics.compute
df.copy.dropna
targets.torch.from_numpy.type
regressors_df.copy.reset_index.copy
logger.setLevel
numpy.append
df_name.df_dict_events.unique
self.config_normalization.init_data_params
cp_t.append
find_valid_time_interval_for_cv
plot_trend
logging.getLogger.getEffectiveLevel
val_metrics.items
self.loss_func_name.torch.nn.modules.loss.getattr
self.config_country_holidays.init_holidays
abs
self.metrics.set_shift_scale
tick.set_rotation
m.config_normalization.get_data_params
neuralprophet.utils.set_y_as_percent.grid
install_hooks
additive_future_regressors.append
plotly.graph_objs.Layout
df_name.other_df.other_df.reset_index.copy.drop
holidays.HolidayBase.__init__
average_loss.data.item
subprocess.check_call
fig.add_subplot.set_ylabel
self._train_minimal
torch.save
neuralprophet.metrics.MetricsCollection.reset
self._get_maybe_extend_periods
loss.sum.mean
i.name.self.covar_nets
neuralprophet.utils.get_holidays_from_country
self._maybe_extend_df
col.df.any
numpy.expand_dims
self._train_epoch
numpy.arange
pandas.Timedelta
features.torch.from_numpy.type
col.df.count
comp_name.fcst.notna
neuralprophet.utils.create_event_names_for_offsets
numpy.argmax
plot_trend_change
neuralprophet.metrics.MetricsCollection.add_specific_target
predicted.squeeze.detach.numpy
neuralprophet.df_utils.convert_events_to_features
multiplicative_future_regressors.append
numpy.max
period.np.floor.astype
m.model.get_trend_deltas.detach
logging.FileHandler.setFormatter
pandas.Series
df.reset_index.unique
torch.nn.ModuleDict
self._predict_raw
config_season.periods.items
plotly.graph_objs.layout.XAxis.update
multiplicative_events_dims.sort_values.reset_index
unfold_dict_of_folds
neuralprophet.utils.set_y_as_percent.plot
self.MAE.super.__init__
diffs.unsqueeze
datetime.date
neuralprophet.utils.print_epoch_metrics
df.reset_index.max
format.split
format.lower
super
next
self.model.parameters
loss.sum.mean.backward
y_season.data.numpy
neuralprophet.plot_forecast_plotly.plot
limit_linear.limit_linear.rolling.series.rolling.mean
self.config_train.get_scheduler
numpy.dstack
neuralprophet.plot_forecast.plot_components
numpy.concatenate.detach
self.plot_last_forecast
df.groupby
self.config_train.find_learning_rate
pandas.concat.reset_index
numpy.quantile
values.items
neuralprophet.plot_model_parameters.plot_weekly
torch.from_numpy.detach
logging.captureWarnings
df_y.dt.to_pydatetime
neuralprophet.df_utils.get_max_num_lags
dataclasses.field
self.config_covar.keys
multiplicative_events_dims.sort_values.reset_index.sort_values
column.df.fillna
lunarcalendar.Lunar
numpy.concatenate
logging.Formatter
neuralprophet.df_utils.double_crossvalidation_split_df
m.model.quantiles.index
neuralprophet.metrics.MetricsCollection.update
numpy.delete
i.self.layers.reshape
column.df.isnull
name.df.replace
numpy.min
model.get_reg_weights
name.data_params.shift.name.df.sub.div
self.batch_metrics.extend
pandas.date_range
warnings.simplefilter
merge_dataframes.reset_index
list.append
self.get_stored_as_df
self._normalize
data_params_definition
df.loc.isnull
METRICS.keys
df.reset_index.min
neuralprophet.utils.config_season_to_model_dims
param.detach
neuralprophet.utils.reg_func_season
neuralprophet.plot_model_parameters.plot_custom_season
fcst.dt.minute.all
r.df.set_index.reindex.rename_axis
self.optimizer.step
torch.nn.init.kaiming_normal_
int
data_columns.extend
numpy.linspace
app.add_css_file
model.get_event_weights
type
neuralprophet.metrics.MetricsCollection.compute
losses.np.array.np.gradient.argmin
plotly.graph_objs.Bar
merge_dataframes.sort_values
self.__handle_missing_data
torch.manual_seed
torch.exp
self.loss_func
i.self.layers
torch.max
m.model.get_event_weights
df_fold_aux.copy.groupby
df.copy.drop
self._init_train_loader
self.config_regressors.keys
torch.mean
multiplicative_regressor_feature_windows.append
neuralprophet.utils.set_y_as_percent.legend
round
unfold_dict_of_folds.append
neuralprophet.plot_model_parameters_plotly.get_dynamic_axis_range
nblink_file.endswith
app.connect
self.model.compute_components
name.self.value_metrics.update
matplotlib.dates.MonthLocator
data.torch.from_numpy.type
get_forecast_component_props
self.config_events.keys
min
convert_str_to_num_freq
any
self.scalar_features_effects
other_df.drop.drop
other_df.drop.unique
self._compute_quantile_forecasts_from_diffs
df_t.copy
ValueError
numpy.log10
self._check_dataframe
scale.total_seconds
mask.df_i.copy.copy
y_events_override.get
torch.squeeze
warnings.catch_warnings
format.notnull
self.config_train.get_reg_delay_weight
regressors_df.copy.reset_index
holiday.country_specific_holidays_dict.append
events.regressors.covariates.check_y.df_i.check_single_dataframe.copy
lagged_components.append
self.model.ar_weights.detach.numpy
self.drop_nan_after_init
logging.StreamHandler.setFormatter
torch_lr_finder.LRFinder.reset
numpy.abs
str
neuralprophet.time_dataset.fourier_series_t
neuralprophet.utils_torch.penalize_nonzero
self.config_trend.n_changepoints.np.arange.astype
neuralprophet.utils.reg_func_trend
logging.getLogger.warning
locals
y_holidays_override.get
distribution.max
self.quantiles.insert
self.metrics.update
self.bias.unsqueeze.unsqueeze
params.unsqueeze.unsqueeze
multiplicative_events.columns.tolist
self.quantiles.torch.tensor.unsqueeze
self.init_after_tabularized
self.quantiles.sort
pandas.concat.copy
model.parameters
print
m.model.get_reg_weights.detach
fourier_series
torch.ones
neuralprophet.plot_model_parameters.plot_yearly
index.append
neuralprophet.df_utils.crossvalidation_split_df
sum
fourier_series_t
f.read.splitlines
neuralprophet.df_utils.infer_frequency
comp_name.fcst.notna.notna
plotly.graph_objs.layout.XAxis
dateutil.easter.easter
_split_df
self._create_dataset
df_name.other_df.other_df.reset_index.copy
ax.axes.get_legend_handles_labels
t_end.t_start.pd.Series.dt.to_pydatetime.strftime
prep_or_copy_df
self._evaluate_epoch
self.all_seasonalities.keys
self.optimizer.zero_grad
self.scheduler.step
loss.sum.mean.sum
self.value_metrics.keys
self.trend.detach
events.sort
neuralprophet.configure.Covar
additive_regressors.columns.tolist
quantile_index.m.model.bias.detach.numpy
self.config_train.quantiles.index
neuralprophet.time_dataset.make_country_specific_holidays_df.items
features.unsqueeze
neuralprophet.df_utils.split_df
split_idx_train.df.copy.iloc.reset_index
torch.zeros
df.reset_index.notna
os.remove
format
target.numpy.numpy
self.config_train.set_auto_batch_epoch
numpy.gradient
find_time_threshold
plot_multiforecast_component
plotly.subplots.make_subplots.add_trace
split_idx_val.df.copy.iloc.reset_index
mask.df_i.copy
country.hdays_part1.getattr
self._validate_column_name
days.day_name.day_name
list
numpy.issubdtype
set
self.config_normalization.get_data_params
m.predict_trend
self._no_sample_error
dict
m.model.get_trend_deltas.detach.numpy
self.trend_m.unsqueeze.unsqueeze
TimeDataset
pandas.concat.iterrows
convert_events_to_features.reset_index
name.self.season_params.unsqueeze.unsqueeze
sys.path.insert
torch.nn.Parameter
self.update_values
neuralprophet.configure.AllSeason
self.combined_timedataset.append
neuralprophet.plot_model_parameters_plotly.plot_parameters
neuralprophet.utils.config_events_to_model_dims
Season
neuralprophet.utils.HiddenPrints
torch.ones_like.unsqueeze
progress.lower
m.model.config_covar.keys
numpy.random.seed
neuralprophet.plot_model_parameters.plot_parameters
t.unsqueeze.unsqueeze
datetime.timedelta
df.reset_index.isnull
name.self.season_params.unsqueeze
torch.nn.functional.relu
matplotlib.dates.AutoDateLocator
matplotlib.dates.num2date
m.config_covar.keys
quantile_index.m.model.trend_k0.detach
neuralprophet.plot_model_parameters.predict_season_from_dates
neuralprophet.df_utils.create_dict_for_events_or_regressors
neuralprophet.utils.reg_func_regressors
live_out.append
t.self.model.trend.detach.numpy
comp.lower
quantile_index.m.model.trend_k0.detach.numpy
df_name.df.df.max
logging.getLogger.error
nan_idx.append
numpy.insert
self.model.trend
fig.add_subplot.set_xlabel
format.update
self._get_time_based_sample_weight
predicting.freq.df_i.self.__handle_missing_data.copy
neuralprophet.time_net.TimeNet
country.hdays_part2.getattr
tensor.np.array.np.isnan.any
numpy.round
os.path.join
pandas.concat.groupby
quantile_index.m.model.bias.detach
comp.lower.lower
neuralprophet.metrics.ValueMetric
df.set_index.reindex
neuralprophet.df_utils.init_data_params
self.model.forward
df.ds.unique
self.model.ar_weights.detach
tick.set_ha
additive_events_dims.sort_values.reset_index
comp_name.fcst.rolling
datetime.datetime.dates.dt.total_seconds
ax.get_yticks
multiplicative_axes.append
</pre>
</details>

@developer
Could please help me check this issue?
May I pull a request to fix it?
Thank you very much.

**Comment by noxan** [comment]
@PyDeps thanks for the feedback and totally agree with your points. Would be glad to see a pull request addressing those concerns :)
