### ISSUE TITLE
[bug] Model training much more slowly after Lightning Migration

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#949]
Using the autoregression_yosemite_temps.ipynb and the following code as the example: 

```
%%time
m = NeuralProphet(
    n_lags=12,
    changepoints_range=0.95,
    n_changepoints=30,
    weekly_seasonality=False,
)
metrics = m.fit(df)

```

in `v0.4.2`, the training time took **2.25 min**:

![image](https://user-images.githubusercontent.com/13785749/201490920-45fbcf2e-386f-4cd2-98c9-214af54598f7.png)

However, after the Lightning Migration, the training time took **10 min**, or 4x longer:

![image](https://user-images.githubusercontent.com/13785749/201490963-305bafd9-33f0-4674-a3e6-2c6ca22d4c2f.png)

I used the same machine (Linux on AWS SageMaker Studio Labs) to run both, one after the other. Please advise.

Thanks.

**Comment by karl-richter** [comment]
@Kevin-Chen0 thanks for raising this, I am having a look!
