### ISSUE TITLE
[refactor] Reduce and restructure the unit tests to make it less bloated

### ISSUE THREAD

**Issue by Kevin-Chen0** [ourownstory/neural_prophet#950]
There are currently 104 separate unit tests in the `tests/` directory, taking at least several minutes to run through.

![image](https://user-images.githubusercontent.com/13785749/201538644-4929993c-aa9a-4011-bd53-69f60ba0e724.png)

A lot of the tests are created independently by separate developers in order the maintain the code coverage for their PR. These are potential coverage overlaps or redundancy between these tests. We need to restructure the unit tests in order to reduce the number of tests yet maintainer, if not improve, then code coverage %.

Other testing improvement suggestions:
- [Pytest Fixtures and Parameters](https://medium.com/ideas-at-igenius/fixtures-and-parameters-testing-code-with-pytest-d8603abb390a)
- [Property-based Testing](https://www.freecodecamp.org/news/intro-to-property-based-testing-in-python-6321e0c2f8b/)

**Comment by leoniewgnr** [comment]
PR will be closed for V2 release, but ideas and feature request are saved and might be realized in V2.
