### ISSUE TITLE
Rename plot_forecast.py and plot_model_parameters.py to xxx_matplotlib.py

### ISSUE THREAD

**Issue by LeonieFreisinger** [ourownstory/neural_prophet#964]
Rename plot_forecast.py and plot_model_parameters.py to plot_forecast._matplotlib.py and plot_model_parameters_matplotlib.py to be consistent

**Comment by LeonieFreisinger** [comment]
> Hi @LeonieFreisinger Can I take this issue ?

@SaumyaBhushan Yes sure, go ahead

**Comment by SaumyaBhushan** [comment]
Hi @LeonieFreisinger Already submitted a PR. can you please review?

**Comment by LeonieFreisinger** [comment]
> Hi @LeonieFreisinger Already submitted a PR. can you please review?

@SaumyaBhushan Thanks for approaching the issue. Please check on the renamed file again. There is an unnecessary "." in there. Furthermore, please make sure to change the name as well in every import statement.

**Comment by SaumyaBhushan** [comment]
Hi @LeonieFreisinger ! please let me know if anything else need to be changed.
