### ISSUE TITLE
Unify the naming of variables - "num" and "nb"

### ISSUE THREAD

**Issue by karl-richter** [ourownstory/neural_prophet#969]
As a conversion, variables containing a count are named beginning with "num", eg. "num_lagged_regressors". However, in some instances developers named variables to start with "nb" instead of "num". This can eg. be oberserved in the `fit()` method with `self.nb_trends_modelled`. The naming should be unified, aka all "nb" should be replaced with "num".

**Comment by SaumyaBhushan** [comment]
Hi @karl-richter Can I work on this ?

**Comment by karl-richter** [comment]
@SaumyaBhushan from my side yes - if you are uncertain at times just reach out.

**Comment by SaumyaBhushan** [comment]
Sure @karl-richter . Thanks a lot.

**Comment by SaumyaBhushan** [comment]
@noxan @karl-richter Can you please review the pull request?

**Comment by noxan** [comment]
Closed with #994
