### ISSUE TITLE
Add support for timezones

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#970]
**Is your feature request related to a problem? Please describe.**

- NeuralProphet fails if the `ds` values have a timezone definition

**Describe the solution you'd like**

- Would be great to have NeuralProphet convert the timezone into UTC or unix timestamp internally and not fail.
- Possibly show an `info` logging about the automatic transformation of timezones

**Sample dataset with timezone**
https://www.kaggle.com/datasets/nicholasjhana/energy-consumption-generation-prices-and-weather

**Source reference**
https://github.com/ourownstory/neural_prophet/blob/acf053f61ff2d63e9ab473d22d7fc22489d121e7/neuralprophet/df_utils.py#L442-L443

**Comment by SaumyaBhushan** [comment]
Hi @noxan Can I work on this ?

**Comment by noxan** [comment]
@SaumyaBhushan sure, I've assigned the issue to you. If there are any questions happy to support you :)

**Comment by SaumyaBhushan** [comment]
Thanks @noxan

**Comment by leoniewgnr** [comment]
Hey @SaumyaBhushan, is it correct, that you don't want to work on this anymore? Then I would be happy to work on this.

**Comment by karl-richter** [comment]
Resolved by #1085.
